/**
 * Destinations travel.gc.ca / voyage.gc.ca publish advice for (server only, never imported by the renderer):
 * ISO code, English name, French name, exactly as Global Affairs Canada spells them. They are the names the
 * travel health notices use in their "Location" column, so a notice's places match this list one to one.
 * Source: data.international.gc.ca/travel-voyage/index-alpha-eng.json (the open data behind
 * travel.gc.ca/travelling/advisories), 230 destinations, generated 2026-10-01 and checked that day against every
 * place named in the EN and FR notice tables.
 */
export const DESTINATIONS: readonly (readonly [iso: string, en: string, fr: string])[] = [
  ['AF', 'Afghanistan', 'Afghanistan'],
  ['AL', 'Albania', 'Albanie'],
  ['DZ', 'Algeria', 'Algérie'],
  ['AS', 'American Samoa', 'Samoa américaines'],
  ['AD', 'Andorra', 'Andorre'],
  ['AO', 'Angola', 'Angola'],
  ['AI', 'Anguilla', 'Anguilla'],
  ['AQ', 'Antarctica', 'Antarctique'],
  ['AG', 'Antigua and Barbuda', 'Antigua-et-Barbuda'],
  ['AR', 'Argentina', 'Argentine'],
  ['AM', 'Armenia', 'Arménie'],
  ['AW', 'Aruba', 'Aruba'],
  ['AU', 'Australia', 'Australie'],
  ['AT', 'Austria', 'Autriche'],
  ['AZ', 'Azerbaijan', 'Azerbaïdjan'],
  ['PT-20', 'Azores', 'Açores'],
  ['BS', 'Bahamas', 'Bahamas'],
  ['BH', 'Bahrain', 'Bahreïn'],
  ['BD', 'Bangladesh', 'Bangladesh'],
  ['BB', 'Barbados', 'Barbade'],
  ['BY', 'Belarus', 'Bélarus'],
  ['BE', 'Belgium', 'Belgique'],
  ['BZ', 'Belize', 'Belize'],
  ['BJ', 'Benin', 'Bénin'],
  ['BM', 'Bermuda', 'Bermudes'],
  ['BT', 'Bhutan', 'Bhoutan'],
  ['BO', 'Bolivia', 'Bolivie'],
  ['BQ', 'Bonaire', 'Bonaire'],
  ['BA', 'Bosnia and Herzegovina', 'Bosnie-Herzégovine'],
  ['BW', 'Botswana', 'Botswana'],
  ['BR', 'Brazil', 'Brésil'],
  ['VG', 'British Virgin Islands', 'Îles Vierges britanniques'],
  ['BN', 'Brunei', 'Brunéi'],
  ['BG', 'Bulgaria', 'Bulgarie'],
  ['BF', 'Burkina Faso', 'Burkina Faso'],
  ['BI', 'Burundi', 'Burundi'],
  ['CV', 'Cabo Verde', 'Cabo Verde'],
  ['KH', 'Cambodia', 'Cambodge'],
  ['CM', 'Cameroon', 'Cameroun'],
  ['IC', 'Canary Islands', 'Îles Canaries'],
  ['KY', 'Cayman Islands', 'Îles Caïmans'],
  ['CF', 'Central African Republic', 'République centrafricaine'],
  ['TD', 'Chad', 'Tchad'],
  ['CL', 'Chile', 'Chili'],
  ['CN', 'China', 'Chine'],
  ['CO', 'Colombia', 'Colombie'],
  ['KM', 'Comoros', 'Comores'],
  ['CK', 'Cook Islands', 'Îles Cook'],
  ['CR', 'Costa Rica', 'Costa Rica'],
  ['HR', 'Croatia', 'Croatie'],
  ['CU', 'Cuba', 'Cuba'],
  ['CW', 'Curaçao', 'Curaçao'],
  ['CY', 'Cyprus', 'Chypre'],
  ['CZ', 'Czechia', 'Tchéquie'],
  ['CI', "Côte d'Ivoire (Ivory Coast)", "Côte d'Ivoire"],
  ['CD', 'Democratic Republic of Congo (Kinshasa)', 'République démocratique du Congo (Kinshasa)'],
  ['DK', 'Denmark', 'Danemark'],
  ['DJ', 'Djibouti', 'Djibouti'],
  ['DM', 'Dominica', 'Dominique'],
  ['DO', 'Dominican Republic', 'République dominicaine'],
  ['EC', 'Ecuador', 'Équateur'],
  ['EG', 'Egypt', 'Égypte'],
  ['SV', 'El Salvador', 'Salvador'],
  ['GQ', 'Equatorial Guinea', 'Guinée équatoriale'],
  ['ER', 'Eritrea', 'Érythrée'],
  ['EE', 'Estonia', 'Estonie'],
  ['SZ', 'Eswatini', 'Eswatini'],
  ['ET', 'Ethiopia', 'Éthiopie'],
  ['FK', 'Falkland Islands', 'Îles Falkland'],
  ['FJ', 'Fiji', 'Fidji'],
  ['FI', 'Finland', 'Finlande'],
  ['FR', 'France', 'France'],
  ['GF', 'French Guiana', 'Guyane française'],
  ['PF', 'French Polynesia', 'Polynésie française'],
  ['GA', 'Gabon', 'Gabon'],
  ['GM', 'Gambia, The', 'Gambie'],
  ['GE', 'Georgia', 'Géorgie'],
  ['DE', 'Germany', 'Allemagne'],
  ['GH', 'Ghana', 'Ghana'],
  ['GI', 'Gibraltar', 'Gibraltar'],
  ['GR', 'Greece', 'Grèce'],
  ['GL', 'Greenland', 'Groenland'],
  ['GD', 'Grenada', 'Grenade'],
  ['GP', 'Guadeloupe', 'Guadeloupe'],
  ['GU', 'Guam', 'Guam'],
  ['GT', 'Guatemala', 'Guatemala'],
  ['GN', 'Guinea', 'Guinée'],
  ['GW', 'Guinea-Bissau', 'Guinée-Bissau'],
  ['GY', 'Guyana', 'Guyana'],
  ['HT', 'Haiti', 'Haïti'],
  ['HN', 'Honduras', 'Honduras'],
  ['HK', 'Hong Kong', 'Hong Kong'],
  ['HU', 'Hungary', 'Hongrie'],
  ['IS', 'Iceland', 'Islande'],
  ['IN', 'India', 'Inde'],
  ['ID', 'Indonesia', 'Indonésie'],
  ['IR', 'Iran', 'Iran'],
  ['IQ', 'Iraq', 'Iraq'],
  ['IE', 'Ireland', 'Irlande'],
  ['IL', 'Israel and Palestine', 'Israël et la Palestine'],
  ['IT', 'Italy', 'Italie'],
  ['JM', 'Jamaica', 'Jamaïque'],
  ['JP', 'Japan', 'Japon'],
  ['JO', 'Jordan', 'Jordanie'],
  ['KZ', 'Kazakhstan', 'Kazakhstan'],
  ['KE', 'Kenya', 'Kenya'],
  ['KI', 'Kiribati', 'Kiribati'],
  ['XK', 'Kosovo', 'Kosovo'],
  ['KW', 'Kuwait', 'Koweït'],
  ['KG', 'Kyrgyzstan', 'Kirghizistan'],
  ['LA', 'Laos', 'Laos'],
  ['LV', 'Latvia', 'Lettonie'],
  ['LB', 'Lebanon', 'Liban'],
  ['LS', 'Lesotho', 'Lesotho'],
  ['LR', 'Liberia', 'Libéria'],
  ['LY', 'Libya', 'Libye'],
  ['LI', 'Liechtenstein', 'Liechtenstein'],
  ['LT', 'Lithuania', 'Lituanie'],
  ['LU', 'Luxembourg', 'Luxembourg'],
  ['MO', 'Macao', 'Macao'],
  ['MG', 'Madagascar', 'Madagascar'],
  ['MW', 'Malawi', 'Malawi'],
  ['MY', 'Malaysia', 'Malaisie'],
  ['MV', 'Maldives', 'Maldives'],
  ['ML', 'Mali', 'Mali'],
  ['MT', 'Malta', 'Malte'],
  ['MH', 'Marshall Islands', 'Îles Marshall'],
  ['MQ', 'Martinique', 'Martinique'],
  ['MR', 'Mauritania', 'Mauritanie'],
  ['MU', 'Mauritius', 'Maurice'],
  ['YT', 'Mayotte', 'Mayotte'],
  ['MX', 'Mexico', 'Mexique'],
  ['FM', 'Micronesia (FSM)', 'Micronésie (EFM)'],
  ['MD', 'Moldova', 'Moldova'],
  ['MC', 'Monaco', 'Monaco'],
  ['MN', 'Mongolia', 'Mongolie'],
  ['ME', 'Montenegro', 'Monténégro'],
  ['MS', 'Montserrat', 'Montserrat'],
  ['MA', 'Morocco', 'Maroc'],
  ['MZ', 'Mozambique', 'Mozambique'],
  ['MM', 'Myanmar', 'Myanmar'],
  ['NA', 'Namibia', 'Namibie'],
  ['NR', 'Nauru', 'Nauru'],
  ['NP', 'Nepal', 'Népal'],
  ['NL', 'Netherlands', 'Pays-Bas'],
  ['NC', 'New Caledonia', 'Nouvelle-Calédonie'],
  ['NZ', 'New Zealand', 'Nouvelle-Zélande'],
  ['NI', 'Nicaragua', 'Nicaragua'],
  ['NE', 'Niger', 'Niger'],
  ['NG', 'Nigeria', 'Nigéria'],
  ['NU', 'Niue', 'Niue'],
  ['KP', 'North Korea', 'Corée du Nord'],
  ['MK', 'North Macedonia', 'Macédoine du Nord'],
  ['MP', 'Northern Marianas', 'Îles Mariannes du Nord'],
  ['NO', 'Norway', 'Norvège'],
  ['OM', 'Oman', 'Oman'],
  ['PK', 'Pakistan', 'Pakistan'],
  ['PW', 'Palau', 'Palaos'],
  ['PA', 'Panama', 'Panama'],
  ['PG', 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée'],
  ['PY', 'Paraguay', 'Paraguay'],
  ['PE', 'Peru', 'Pérou'],
  ['PH', 'Philippines', 'Philippines'],
  ['PL', 'Poland', 'Pologne'],
  ['PT', 'Portugal', 'Portugal'],
  ['PR', 'Puerto Rico', 'Porto Rico'],
  ['QA', 'Qatar', 'Qatar'],
  ['CG', 'Republic of Congo (Brazzaville)', 'République du Congo (Brazzaville)'],
  ['RO', 'Romania', 'Roumanie'],
  ['RU', 'Russia', 'Russie'],
  ['RW', 'Rwanda', 'Rwanda'],
  ['RE', 'Réunion', 'La Réunion'],
  ['KN', 'Saint Kitts and Nevis', 'Saint-Kitts-et-Nevis'],
  ['LC', 'Saint Lucia', 'Sainte-Lucie'],
  ['MF', 'Saint Martin', 'Saint-Martin'],
  ['VC', 'Saint Vincent & the Grenadines', 'Saint-Vincent-et-Grenadines'],
  ['BL', 'Saint-Barthélemy', 'Saint-Barthélemy'],
  ['PM', 'Saint-Pierre-et-Miquelon', 'Saint-Pierre-et-Miquelon'],
  ['WS', 'Samoa', 'Samoa'],
  ['SM', 'San Marino', 'Saint-Marin'],
  ['ST', 'Sao Tome and Principe', 'Sao Tomé-et-Principe'],
  ['SA', 'Saudi Arabia', 'Arabie saoudite'],
  ['SN', 'Senegal', 'Sénégal'],
  ['RS', 'Serbia', 'Serbie'],
  ['SC', 'Seychelles', 'Seychelles'],
  ['SL', 'Sierra Leone', 'Sierra Leone'],
  ['SG', 'Singapore', 'Singapour'],
  ['SX', 'Sint Maarten', 'Sint Maarten'],
  ['SK', 'Slovakia', 'Slovaquie'],
  ['SI', 'Slovenia', 'Slovénie'],
  ['SB', 'Solomon Islands', 'Îles Salomon'],
  ['SO', 'Somalia', 'Somalie'],
  ['ZA', 'South Africa', 'Afrique du Sud'],
  ['KR', 'South Korea', 'Corée du Sud'],
  ['SS', 'South Sudan', 'Soudan du Sud'],
  ['ES', 'Spain', 'Espagne'],
  ['LK', 'Sri Lanka', 'Sri Lanka'],
  ['SD', 'Sudan', 'Soudan'],
  ['SR', 'Suriname', 'Suriname'],
  ['SE', 'Sweden', 'Suède'],
  ['CH', 'Switzerland', 'Suisse'],
  ['SY', 'Syria', 'Syrie'],
  ['TW', 'Taiwan', 'Taïwan'],
  ['TJ', 'Tajikistan', 'Tadjikistan'],
  ['TZ', 'Tanzania', 'Tanzanie'],
  ['TH', 'Thailand', 'Thaïlande'],
  ['TL', 'Timor-Leste (East Timor)', 'Timor-Leste (Timor oriental)'],
  ['TG', 'Togo', 'Togo'],
  ['TK', 'Tokelau', 'Tokelau'],
  ['TO', 'Tonga', 'Tonga'],
  ['TT', 'Trinidad and Tobago', 'Trinité-et-Tobago'],
  ['TN', 'Tunisia', 'Tunisie'],
  ['TM', 'Turkmenistan', 'Turkménistan'],
  ['TC', 'Turks and Caicos Islands', 'Îles Turks et Caicos'],
  ['TV', 'Tuvalu', 'Tuvalu'],
  ['TR', 'Türkiye', 'Türkiye'],
  ['UG', 'Uganda', 'Ouganda'],
  ['UA', 'Ukraine', 'Ukraine'],
  ['AE', 'United Arab Emirates', 'Émirats arabes unis'],
  ['GB', 'United Kingdom', 'Royaume-Uni'],
  ['US', 'United States', 'États-Unis'],
  ['UY', 'Uruguay', 'Uruguay'],
  ['UZ', 'Uzbekistan', 'Ouzbékistan'],
  ['VU', 'Vanuatu', 'Vanuatu'],
  ['VE', 'Venezuela', 'Venezuela'],
  ['VN', 'Vietnam', 'Vietnam'],
  ['VI', 'Virgin Islands (U.S.)', 'Îles Vierges américaines'],
  ['YE', 'Yemen', 'Yémen'],
  ['ZM', 'Zambia', 'Zambie'],
  ['ZW', 'Zimbabwe', 'Zimbabwe'],
];
