#!/usr/bin/env node
// Renders `messages/pt.json` and `messages/en.json` from `catalog.data.json`.
//
//   node src/countries/br/messages/render.mjs
//
// One source of truth for both languages, so EN/PT parity is true by construction rather than by review.
// The renderer refuses to write if the two languages disagree on placeholders, if a key is missing a
// language, or if a string contains something a human could not have typed. `pnpm check:i18n --country br`
// then checks the result against the keys core and the widgets actually use.
import { readFileSync, writeFileSync } from 'node:fs';

const DATA_URL = new URL('./catalog.data.json', import.meta.url);
const raw = JSON.parse(readFileSync(DATA_URL, 'utf8'));

/** `services.<id>` is authored compactly as {n,d,s,g}; the catalog wants four flat keys per service. */
const FIELD = { name: 'n', desc: 'd', starter: 's', go: 'g' };

const problems = [];
const fail = (m) => {
  problems.push(m);
  console.log('✗ ' + m);
};

/**
 * Keys the landing composes into a sentence, so a leading or trailing space is part of the value.
 * Mirrors the same three keys in the Canada catalog.
 */
const FRAGMENTS = new Set(['showcase.tax.daysLeft', 'flag.demo.a2', 'flag.demo.a3']);

/**
 * Markers of the failure mode that actually happened while this pack was being written: Portuguese prose
 * with a stray machine token welded onto a word. Each one is a real string this renderer caught.
 */
const GARBLE = ['此种', 'IGО Disabled', 'IG Disabled', '运费', '琛', '坐在', 'Chapada e运费', 'Contributor.', 'Deduzimos.', 'adopters e operá-lo'];

/** {placeholders} in a string, per the ICU subset in src/lib/i18n/format.ts. */
const placeholders = (s) => new Set([...s.matchAll(/\{([A-Za-z_][\w]*)(?=[,}])/g)].map((m) => m[1]));
const samePlaceholders = (a, b) => {
  const pa = placeholders(a);
  const pb = placeholders(b);
  return pa.size === pb.size && [...pa].every((x) => pb.has(x));
};

// ---- flatten to one {key, pt, en} list ----------------------------------------------------------
const flat = [];
for (const [key, value] of Object.entries(raw)) {
  if (key.startsWith('_')) continue;
  if (key.startsWith('services.') && !key.split('.').includes('name') && 'n' in value) {
    const id = key.split('.')[1];
    for (const [field, short] of Object.entries(FIELD)) {
      flat.push({ key: `services.${id}.${field}`, pt: value[short].pt, en: value[short].en });
    }
    continue;
  }
  if (!value || typeof value !== 'object' || !('pt' in value) || !('en' in value)) {
    fail(`${key}: needs both "pt" and "en"`);
    continue;
  }
  flat.push({ key, pt: value.pt, en: value.en });
}

// ---- validate every entry before writing anything -------------------------------------------------
for (const entry of flat) {
  for (const lang of ['pt', 'en']) {
    const s = entry[lang];
    if (typeof s !== 'string' || !s.trim()) {
      fail(`${entry.key}.${lang}: empty`);
      continue;
    }
    // A few keys are sentence FRAGMENTS the landing composes around them ("…{count} dias restantes"),
    // so a leading or trailing space is intentional there and only there.
    if (s !== s.trim() && !FRAGMENTS.has(entry.key)) fail(`${entry.key}.${lang}: leading or trailing whitespace`);
    if (/[`]/.test(s)) fail(`${entry.key}.${lang}: backtick`);
    if (/[一-鿿Ѐ-ӿ぀-ヿ]/.test(s)) fail(`${entry.key}.${lang}: unexpected script`);
    if (/ {2}/.test(s)) fail(`${entry.key}.${lang}: double space`);
    for (const marker of GARBLE) if (s.includes(marker)) fail(`${entry.key}.${lang}: garbled text "${marker}"`);
  }
  if (!samePlaceholders(entry.pt, entry.en)) {
    fail(`${entry.key}: placeholders differ (pt ${[...placeholders(entry.pt)]} vs en ${[...placeholders(entry.en)]})`);
  }
}

const dupes = flat.map((e) => e.key).filter((k, i, a) => a.indexOf(k) !== i);
for (const d of new Set(dupes)) fail(`${d}: duplicated key`);

if (problems.length) {
  console.log(`\n${problems.length} problem(s); nothing written`);
  process.exit(1);
}

// ---- write, in the same key order, so the two files diff cleanly -----------------------------------
const byLang = (lang) => Object.fromEntries(flat.map((e) => [e.key, e[lang]]));
const header = (lang) =>
  [
    '{',
    `  "_generated": "GENERATED by node src/countries/br/messages/render.mjs from catalog.data.json — edit that, never this file. ${lang === 'pt' ? 'Portuguese is the product language.' : 'English is the reviewed second language.'}",`,
  ].join('\n');

for (const lang of ['pt', 'en']) {
  const body = JSON.stringify(byLang(lang), null, 2);
  const out = body.replace('{\n', `${header(lang)}\n`, 1);
  writeFileSync(new URL(`./${lang}.json`, import.meta.url), out + '\n');
  console.log(`✓ messages/${lang}.json (${flat.length} keys)`);
}
console.log(`\n✓ ${flat.length} keys rendered in pt and en, placeholders matched`);