/**
 * Destinations covered by Global Affairs Canada's Travel Advice and Advisories (230 on 2026-09-30), with
 * their English/French names and travel.gc.ca / voyage.gc.ca page slugs. Generated from
 * https://data.international.gc.ca/travel-voyage/index-alpha-eng.json (generated 2026-09-29 16:20 EDT).
 * Used to find the destination named in a question (no network needed) and to link the official page
 * even when the live feed is down. Server-side only (tool + scenarios); the renderer never imports it.
 */

/** [code, English name, French name, travel.gc.ca slug, voyage.gc.ca slug] */
export type CountryRow = readonly [iso: string, en: string, fr: string, slugEn: string, slugFr: string];

export const COUNTRIES: readonly CountryRow[] = [
  ["AF", "Afghanistan", "Afghanistan", "afghanistan", "afghanistan"],
  ["AL", "Albania", "Albanie", "albania", "albanie"],
  ["DZ", "Algeria", "Algérie", "algeria", "algerie"],
  ["AS", "American Samoa", "Samoa américaines", "american-samoa", "samoa-americaines"],
  ["AD", "Andorra", "Andorre", "andorra", "andorre"],
  ["AO", "Angola", "Angola", "angola", "angola"],
  ["AI", "Anguilla", "Anguilla", "anguilla", "anguilla"],
  ["AQ", "Antarctica", "Antarctique", "antarctica", "antarctique"],
  ["AG", "Antigua and Barbuda", "Antigua-et-Barbuda", "antigua-and-barbuda", "antigua-et-barbuda"],
  ["AR", "Argentina", "Argentine", "argentina", "argentine"],
  ["AM", "Armenia", "Arménie", "armenia", "armenie"],
  ["AW", "Aruba", "Aruba", "aruba", "aruba"],
  ["AU", "Australia", "Australie", "australia", "australie"],
  ["AT", "Austria", "Autriche", "austria", "autriche"],
  ["AZ", "Azerbaijan", "Azerbaïdjan", "azerbaijan", "azerbaidjan"],
  ["PT-20", "Azores", "Açores", "azores", "acores"],
  ["BS", "Bahamas", "Bahamas", "bahamas", "bahamas"],
  ["BH", "Bahrain", "Bahreïn", "bahrain", "bahrein"],
  ["BD", "Bangladesh", "Bangladesh", "bangladesh", "bangladesh"],
  ["BB", "Barbados", "Barbade", "barbados", "barbade"],
  ["BY", "Belarus", "Bélarus", "belarus", "belarus"],
  ["BE", "Belgium", "Belgique", "belgium", "belgique"],
  ["BZ", "Belize", "Belize", "belize", "belize"],
  ["BJ", "Benin", "Bénin", "benin", "benin"],
  ["BM", "Bermuda", "Bermudes", "bermuda", "bermudes"],
  ["BT", "Bhutan", "Bhoutan", "bhutan", "bhoutan"],
  ["BO", "Bolivia", "Bolivie", "bolivia", "bolivie"],
  ["BQ", "Bonaire", "Bonaire", "bonaire", "bonaire"],
  ["BA", "Bosnia and Herzegovina", "Bosnie-Herzégovine", "bosnia-and-herzegovina", "bosnie-herzegovine"],
  ["BW", "Botswana", "Botswana", "botswana", "botswana"],
  ["BR", "Brazil", "Brésil", "brazil", "bresil"],
  ["VG", "British Virgin Islands", "Îles Vierges britanniques", "british-virgin-islands", "iles-vierges-britanniques"],
  ["BN", "Brunei", "Brunéi", "brunei", "brunei"],
  ["BG", "Bulgaria", "Bulgarie", "bulgaria", "bulgarie"],
  ["BF", "Burkina Faso", "Burkina Faso", "burkina-faso", "burkina-faso"],
  ["BI", "Burundi", "Burundi", "burundi", "burundi"],
  ["CV", "Cabo Verde", "Cabo Verde", "cabo-verde", "cabo-verde"],
  ["KH", "Cambodia", "Cambodge", "cambodia", "cambodge"],
  ["CM", "Cameroon", "Cameroun", "cameroon", "cameroun"],
  ["IC", "Canary Islands", "Îles Canaries", "canary-islands", "iles-canaries"],
  ["KY", "Cayman Islands", "Îles Caïmans", "cayman-islands", "caimans-iles"],
  ["CF", "Central African Republic", "République centrafricaine", "central-african-republic", "republique-centrafricaine"],
  ["TD", "Chad", "Tchad", "chad", "tchad"],
  ["CL", "Chile", "Chili", "chile", "chili"],
  ["CN", "China", "Chine", "china", "chine"],
  ["CO", "Colombia", "Colombie", "colombia", "colombie"],
  ["KM", "Comoros", "Comores", "comoros", "comores"],
  ["CK", "Cook Islands", "Îles Cook", "cook-islands", "iles-cook"],
  ["CR", "Costa Rica", "Costa Rica", "costa-rica", "costa-rica"],
  ["CI", "Côte d'Ivoire (Ivory Coast)", "Côte d'Ivoire", "cote-d-ivoire-ivory-coast", "cote-d-ivoire"],
  ["HR", "Croatia", "Croatie", "croatia", "croatie"],
  ["CU", "Cuba", "Cuba", "cuba", "cuba"],
  ["CW", "Curaçao", "Curaçao", "curacao", "curacao"],
  ["CY", "Cyprus", "Chypre", "cyprus", "chypre"],
  ["CZ", "Czechia", "Tchéquie", "czechia", "tchequie"],
  ["CD", "Democratic Republic of Congo (Kinshasa)", "République démocratique du Congo (Kinshasa)", "congo-kinshasa", "congo-kinshasa"],
  ["DK", "Denmark", "Danemark", "denmark", "danemark"],
  ["DJ", "Djibouti", "Djibouti", "djibouti", "djibouti"],
  ["DM", "Dominica", "Dominique", "dominica", "dominique"],
  ["DO", "Dominican Republic", "République dominicaine", "dominican-republic", "republique-dominicaine"],
  ["EC", "Ecuador", "Équateur", "ecuador", "equateur"],
  ["EG", "Egypt", "Égypte", "egypt", "egypte"],
  ["SV", "El Salvador", "Salvador", "el-salvador", "salvador"],
  ["GQ", "Equatorial Guinea", "Guinée équatoriale", "equatorial-guinea", "guinee-equatoriale"],
  ["ER", "Eritrea", "Érythrée", "eritrea", "erythree"],
  ["EE", "Estonia", "Estonie", "estonia", "estonie"],
  ["SZ", "Eswatini", "Eswatini", "eswatini", "eswatini"],
  ["ET", "Ethiopia", "Éthiopie", "ethiopia", "ethiopie"],
  ["FK", "Falkland Islands", "Îles Falkland", "falkland-islands", "iles-falkland"],
  ["FJ", "Fiji", "Fidji", "fiji", "fidji"],
  ["FI", "Finland", "Finlande", "finland", "finlande"],
  ["FR", "France", "France", "france", "france"],
  ["GF", "French Guiana", "Guyane française", "french-guiana", "guyane-francaise"],
  ["PF", "French Polynesia", "Polynésie française", "french-polynesia", "polynesie-francaise"],
  ["GA", "Gabon", "Gabon", "gabon", "gabon"],
  ["GM", "Gambia, The", "Gambie", "gambia-the", "gambie"],
  ["GE", "Georgia", "Géorgie", "georgia", "georgie"],
  ["DE", "Germany", "Allemagne", "germany", "allemagne"],
  ["GH", "Ghana", "Ghana", "ghana", "ghana"],
  ["GI", "Gibraltar", "Gibraltar", "gibraltar", "gibraltar"],
  ["GR", "Greece", "Grèce", "greece", "grece"],
  ["GL", "Greenland", "Groenland", "greenland", "groenland"],
  ["GD", "Grenada", "Grenade", "grenada", "grenade"],
  ["GP", "Guadeloupe", "Guadeloupe", "guadeloupe", "guadeloupe"],
  ["GU", "Guam", "Guam", "guam", "guam"],
  ["GT", "Guatemala", "Guatemala", "guatemala", "guatemala"],
  ["GN", "Guinea", "Guinée", "guinea", "guinee"],
  ["GW", "Guinea-Bissau", "Guinée-Bissau", "guinea-bissau", "guinee-bissau"],
  ["GY", "Guyana", "Guyana", "guyana", "guyana"],
  ["HT", "Haiti", "Haïti", "haiti", "haiti"],
  ["HN", "Honduras", "Honduras", "honduras", "honduras"],
  ["HK", "Hong Kong", "Hong Kong", "hong-kong", "hong-kong"],
  ["HU", "Hungary", "Hongrie", "hungary", "hongrie"],
  ["IS", "Iceland", "Islande", "iceland", "islande"],
  ["IN", "India", "Inde", "india", "inde"],
  ["ID", "Indonesia", "Indonésie", "indonesia", "indonesie"],
  ["IR", "Iran", "Iran", "iran", "iran"],
  ["IQ", "Iraq", "Iraq", "iraq", "iraq"],
  ["IE", "Ireland", "Irlande", "ireland", "irlande"],
  ["IL", "Israel and Palestine", "Israël et la Palestine", "israel-and-palestine", "israel-et-palestine"],
  ["IT", "Italy", "Italie", "italy", "italie"],
  ["JM", "Jamaica", "Jamaïque", "jamaica", "jamaique"],
  ["JP", "Japan", "Japon", "japan", "japon"],
  ["JO", "Jordan", "Jordanie", "jordan", "jordanie"],
  ["KZ", "Kazakhstan", "Kazakhstan", "kazakhstan", "kazakhstan"],
  ["KE", "Kenya", "Kenya", "kenya", "kenya"],
  ["KI", "Kiribati", "Kiribati", "kiribati", "kiribati"],
  ["XK", "Kosovo", "Kosovo", "kosovo", "kosovo"],
  ["KW", "Kuwait", "Koweït", "kuwait", "koweit"],
  ["KG", "Kyrgyzstan", "Kirghizistan", "kyrgyzstan", "kirghizistan"],
  ["LA", "Laos", "Laos", "laos", "laos"],
  ["LV", "Latvia", "Lettonie", "latvia", "lettonie"],
  ["LB", "Lebanon", "Liban", "lebanon", "liban"],
  ["LS", "Lesotho", "Lesotho", "lesotho", "lesotho"],
  ["LR", "Liberia", "Libéria", "liberia", "liberia"],
  ["LY", "Libya", "Libye", "libya", "libye"],
  ["LI", "Liechtenstein", "Liechtenstein", "liechtenstein", "liechtenstein"],
  ["LT", "Lithuania", "Lituanie", "lithuania", "lituanie"],
  ["LU", "Luxembourg", "Luxembourg", "luxembourg", "luxembourg"],
  ["MO", "Macao", "Macao", "macao", "macao"],
  ["MG", "Madagascar", "Madagascar", "madagascar", "madagascar"],
  ["MW", "Malawi", "Malawi", "malawi", "malawi"],
  ["MY", "Malaysia", "Malaisie", "malaysia", "malaisie"],
  ["MV", "Maldives", "Maldives", "maldives", "maldives"],
  ["ML", "Mali", "Mali", "mali", "mali"],
  ["MT", "Malta", "Malte", "malta", "malte"],
  ["MH", "Marshall Islands", "Îles Marshall", "marshall-islands", "marshall-iles"],
  ["MQ", "Martinique", "Martinique", "martinique", "martinique"],
  ["MR", "Mauritania", "Mauritanie", "mauritania", "mauritanie"],
  ["MU", "Mauritius", "Maurice", "mauritius", "maurice"],
  ["YT", "Mayotte", "Mayotte", "mayotte", "mayotte"],
  ["MX", "Mexico", "Mexique", "mexico", "mexique"],
  ["FM", "Micronesia (FSM)", "Micronésie (EFM)", "micronesia-fsm", "micronesie-efm"],
  ["MD", "Moldova", "Moldova", "moldova", "moldova"],
  ["MC", "Monaco", "Monaco", "monaco", "monaco"],
  ["MN", "Mongolia", "Mongolie", "mongolia", "mongolie"],
  ["ME", "Montenegro", "Monténégro", "montenegro", "montenegro"],
  ["MS", "Montserrat", "Montserrat", "montserrat", "montserrat"],
  ["MA", "Morocco", "Maroc", "morocco", "maroc"],
  ["MZ", "Mozambique", "Mozambique", "mozambique", "mozambique"],
  ["MM", "Myanmar", "Myanmar", "myanmar", "myanmar"],
  ["NA", "Namibia", "Namibie", "namibia", "namibie"],
  ["NR", "Nauru", "Nauru", "nauru", "nauru"],
  ["NP", "Nepal", "Népal", "nepal", "nepal"],
  ["NL", "Netherlands", "Pays-Bas", "netherlands", "pays-bas"],
  ["NC", "New Caledonia", "Nouvelle-Calédonie", "new-caledonia", "nouvelle-caledonie"],
  ["NZ", "New Zealand", "Nouvelle-Zélande", "new-zealand", "nouvelle-zelande"],
  ["NI", "Nicaragua", "Nicaragua", "nicaragua", "nicaragua"],
  ["NE", "Niger", "Niger", "niger", "niger"],
  ["NG", "Nigeria", "Nigéria", "nigeria", "nigeria"],
  ["NU", "Niue", "Niue", "niue", "niue"],
  ["KP", "North Korea", "Corée du Nord", "north-korea", "coree-nord"],
  ["MK", "North Macedonia", "Macédoine du Nord", "north-macedonia", "macedoine-nord"],
  ["MP", "Northern Marianas", "Îles Mariannes du Nord", "northern-marianas", "mariannes-du-nord-iles"],
  ["NO", "Norway", "Norvège", "norway", "norvege"],
  ["OM", "Oman", "Oman", "oman", "oman"],
  ["PK", "Pakistan", "Pakistan", "pakistan", "pakistan"],
  ["PW", "Palau", "Palaos", "palau", "palaos"],
  ["PA", "Panama", "Panama", "panama", "panama"],
  ["PG", "Papua New Guinea", "Papouasie-Nouvelle-Guinée", "papua-new-guinea", "papouasie-nouvelle-guinee"],
  ["PY", "Paraguay", "Paraguay", "paraguay", "paraguay"],
  ["PE", "Peru", "Pérou", "peru", "perou"],
  ["PH", "Philippines", "Philippines", "philippines", "philippines"],
  ["PL", "Poland", "Pologne", "poland", "pologne"],
  ["PT", "Portugal", "Portugal", "portugal", "portugal"],
  ["PR", "Puerto Rico", "Porto Rico", "puerto-rico", "puerto-rico"],
  ["QA", "Qatar", "Qatar", "qatar", "qatar"],
  ["CG", "Republic of Congo (Brazzaville)", "République du Congo (Brazzaville)", "congo-brazzaville", "congo-brazzaville"],
  ["RE", "Réunion", "La Réunion", "reunion", "la-reunion"],
  ["RO", "Romania", "Roumanie", "romania", "roumanie"],
  ["RU", "Russia", "Russie", "russia", "russie"],
  ["RW", "Rwanda", "Rwanda", "rwanda", "rwanda"],
  ["BL", "Saint-Barthélemy", "Saint-Barthélemy", "saint-barthelemy", "saint-barthelemy"],
  ["KN", "Saint Kitts and Nevis", "Saint-Kitts-et-Nevis", "saint-kitts-and-nevis", "saint-kitts-et-nevis"],
  ["LC", "Saint Lucia", "Sainte-Lucie", "saint-lucia", "sainte-lucie"],
  ["MF", "Saint Martin", "Saint-Martin", "saint-martin", "saint-martin"],
  ["PM", "Saint-Pierre-et-Miquelon", "Saint-Pierre-et-Miquelon", "saint-pierre-et-miquelon", "saint-pierre-et-miquelon"],
  ["VC", "Saint Vincent & the Grenadines", "Saint-Vincent-et-Grenadines", "saint-vincent-the-grenadines", "saint-vincent-et-grenadines"],
  ["WS", "Samoa", "Samoa", "samoa", "samoa"],
  ["SM", "San Marino", "Saint-Marin", "san-marino", "saint-marin"],
  ["ST", "Sao Tome and Principe", "Sao Tomé-et-Principe", "sao-tome-and-principe", "sao-tome-et-principe"],
  ["SA", "Saudi Arabia", "Arabie saoudite", "saudi-arabia", "arabie-saoudite"],
  ["SN", "Senegal", "Sénégal", "senegal", "senegal"],
  ["RS", "Serbia", "Serbie", "serbia", "serbie"],
  ["SC", "Seychelles", "Seychelles", "seychelles", "seychelles"],
  ["SL", "Sierra Leone", "Sierra Leone", "sierra-leone", "sierra-leone"],
  ["SG", "Singapore", "Singapour", "singapore", "singapour"],
  ["SX", "Sint Maarten", "Sint Maarten", "sint-maarten", "sint-maarten"],
  ["SK", "Slovakia", "Slovaquie", "slovakia", "slovaquie"],
  ["SI", "Slovenia", "Slovénie", "slovenia", "slovenie"],
  ["SB", "Solomon Islands", "Îles Salomon", "solomon-islands", "salomon-iles"],
  ["SO", "Somalia", "Somalie", "somalia", "somalie"],
  ["ZA", "South Africa", "Afrique du Sud", "south-africa", "afrique-du-sud"],
  ["KR", "South Korea", "Corée du Sud", "south-korea", "coree-sud"],
  ["SS", "South Sudan", "Soudan du Sud", "south-sudan", "sudan-du-sud"],
  ["ES", "Spain", "Espagne", "spain", "espagne"],
  ["LK", "Sri Lanka", "Sri Lanka", "sri-lanka", "sri-lanka"],
  ["SD", "Sudan", "Soudan", "sudan", "soudan"],
  ["SR", "Suriname", "Suriname", "suriname", "suriname"],
  ["SE", "Sweden", "Suède", "sweden", "suede"],
  ["CH", "Switzerland", "Suisse", "switzerland", "suisse"],
  ["SY", "Syria", "Syrie", "syria", "syrie"],
  ["TW", "Taiwan", "Taïwan", "taiwan", "taiwan"],
  ["TJ", "Tajikistan", "Tadjikistan", "tajikistan", "tadjikistan"],
  ["TZ", "Tanzania", "Tanzanie", "tanzania", "tanzanie"],
  ["TH", "Thailand", "Thaïlande", "thailand", "thailande"],
  ["TL", "Timor-Leste (East Timor)", "Timor-Leste (Timor oriental)", "timor-leste-east-timor", "timor-leste-timor-oriental"],
  ["TG", "Togo", "Togo", "togo", "togo"],
  ["TK", "Tokelau", "Tokelau", "tokelau", "tokelau"],
  ["TO", "Tonga", "Tonga", "tonga", "tonga"],
  ["TT", "Trinidad and Tobago", "Trinité-et-Tobago", "trinidad-and-tobago", "trinite-et-tobago"],
  ["TN", "Tunisia", "Tunisie", "tunisia", "tunisie"],
  ["TR", "Türkiye", "Türkiye", "turkiye", "turkiye"],
  ["TM", "Turkmenistan", "Turkménistan", "turkmenistan", "turkmenistan"],
  ["TC", "Turks and Caicos Islands", "Îles Turks et Caicos", "turks-and-caicos-islands", "iles-turks-et-caicos"],
  ["TV", "Tuvalu", "Tuvalu", "tuvalu", "tuvalu"],
  ["UG", "Uganda", "Ouganda", "uganda", "ouganda"],
  ["UA", "Ukraine", "Ukraine", "ukraine", "ukraine"],
  ["AE", "United Arab Emirates", "Émirats arabes unis", "united-arab-emirates", "emirats-arabes-unis"],
  ["GB", "United Kingdom", "Royaume-Uni", "united-kingdom", "royaume-uni"],
  ["US", "United States", "États-Unis", "united-states", "etats-unis"],
  ["UY", "Uruguay", "Uruguay", "uruguay", "uruguay"],
  ["UZ", "Uzbekistan", "Ouzbékistan", "uzbekistan", "ouzbekistan"],
  ["VU", "Vanuatu", "Vanuatu", "vanuatu", "vanuatu"],
  ["VE", "Venezuela", "Venezuela", "venezuela", "venezuela"],
  ["VN", "Vietnam", "Vietnam", "vietnam", "vietnam"],
  ["VI", "Virgin Islands (U.S.)", "Îles Vierges américaines", "virgin-islands-u-s", "iles-vierges-americaines"],
  ["YE", "Yemen", "Yémen", "yemen", "yemen"],
  ["ZM", "Zambia", "Zambie", "zambia", "zambie"],
  ["ZW", "Zimbabwe", "Zimbabwe", "zimbabwe", "zimbabwe"],
];
