/**
 * Starter scenarios (foundation-owned): a sourced answer for every question the landing page and Menu
 * promote (the hero chips, the rotating examples, the service rows) and their natural rephrasings.
 *
 * They sit at priority 1 so a widget's own scenario (priority >= 6) always wins once it exists.
 * `pnpm check:scenarios --country br` proves every promoted question resolves here, never the fallback.
 *
 * GENERATED by `node src/countries/br/scenarios/render-starters.mjs` from `starters.data.json`.
 * Edit the JSON, never this file.
 *
 * The shape of every answer is the same on purpose: what the rule is, where the official page is, and —
 * where it matters — what this service will not do (take a CPF, promise an amount, file a request).
 * Nothing is asserted that has not been read on the linked page.
 */
import type { Scenario } from '@/lib/scripted/types';

const CHECKED = '2026-10-02';

const STARTERS = [
  {
    "id": "benefits-bpc",
    "match": [
      "bp[cç]",
      "(wh[oòóôõö] q[uùúûü][aàáâãä]l[iìíîï]f[iìíîï][eèéêë]s|wh[oòóôõö] [cç][aàáâãä][nñ] g[eèéêë]t|h[oòóôõö]w d[oòóôõö] [iìíîï] g[eèéêë]t).*(bp[cç]|l[oòóôõö]w [iìíîï][nñ][cç][oòóôõö]m[eèéêë])"
    ],
    "reply": {
      "pt": "# O BPC é para quem tem 65 anos ou mais, ou uma deficiência, e não consegue se sustentar sozinho.\n\nSão três condições: idade de 65 anos ou mais (qualquer idade no caso de deficiência), renda mensal por pessoa da família de até ¼ de salário mínimo, e não receber já um benefício de valor igual ou maior, como aposentadoria ou pensão. O BPC não é aposentadoria: passa por revisão periódica e não aumenta com contribuições.\n\nA renda e o CadÚnico são conferidos no CRAS da sua cidade. O benefício é revisto a cada dois anos.\n\n[1](https://www.gov.br/mds/pt-br)",
      "en": "# The BPC is for people aged 65 or over, or with a disability, who cannot support themselves.\n\nThere are three conditions: being 65 or over (any age for a disability), a household income of up to one-quarter of the minimum wage per person, and not already receiving a benefit of equal or greater value, such as a pension. The BPC is not a pension: it undergoes periodic review and does not rise with contributions.\n\nIncome and the CadÚnico record are checked at your city's CRAS. The benefit is reviewed every two years.\n\n[1](https://www.gov.br/mds/pt-br)"
    },
    "followUps": {
      "pt": [
        "Como faço o CadÚnico?",
        "O BPC conta como aposentadoria?"
      ],
      "en": [
        "How do I register for the CadÚnico?",
        "Does the BPC count as a pension?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "benefits-cadunico",
    "match": [
      "[cç][aàáâãä]d[uùúûü][nñ][iìíîï][cç][oòóôõö]|[cç][aàáâãä]d[aàáâãä]str[oòóôõö] [uùúûü][nñ][iìíîï][cç][oòóôõö]",
      "(h[oòóôõö]w d[oòóôõö][eèéêë]s|wh[aàáâãä]t [iìíîï]s).*[cç][aàáâãä]d[uùúûü][nñ][iìíîï][cç][oòóôõö]",
      "bolsa fam[íi]lia",
      "bolsa fam"
    ],
    "reply": {
      "pt": "# O CadÚnico é o cadastro que abre a porta dos benefícios sociais, e ele é feito no CRAS.\n\nVocê se cadastra na prefeitura ou no CRAS do seu município, com os documentos de quem mora com você. É esse cadastro que define o acesso ao Bolsa Família, ao BPC, ao Auxílio Brasil e a outros programas. Ele não se atualiza sozinho: a família é reconferida periodicamente.\n\nBolsa Família: para famílias com renda per capita até R$ 218, com prioridade para quem tem crianças, adolescentes, gestantes ou nutrizes. O benefício médio varia por composição familiar; consulte o CRAS para o valor exato do seu caso.\n\n[1](https://www.gov.br/mds/pt-br)",
      "en": "# The CadÚnico is the register that opens the door to social benefits, and it is done at the CRAS.\n\nYou register at city hall or at your municipality's CRAS, with the documents of everyone you live with. That register is what decides access to Bolsa Família, the BPC, Auxílio Brasil and other programmes. It does not update itself: the household is re-checked periodically.\n\nBolsa Família: for households with per-capita income up to R$ 218, prioritising those with children, adolescents, pregnant or nursing women. The average benefit varies by family composition; check with your CRAS for the exact amount for your case.\n\n[1](https://www.gov.br/mds/pt-br)"
    },
    "followUps": {
      "pt": [
        "Quem tem direito ao Bolsa Família?",
        "O BPC exige o CadÚnico?"
      ],
      "en": [
        "Who qualifies for Bolsa Família?",
        "Does the BPC require the CadÚnico?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "taxes-irpf",
    "match": [
      "[iìíîï]mp[oòóôõö]st[oòóôõö] d[eèéêë] r[eèéêë][nñ]d[aàáâãä]|\\b[iìíîï]rpf\\b",
      "([iìíîï][nñ][cç][oòóôõö]m[eèéêë] t[aàáâãä]x|h[oòóôõö]w d[oòóôõö] [iìíîï] f[iìíîï]l[eèéêë] my [iìíîï][nñ][cç][oòóôõö]m[eèéêë] t[aàáâãä]x)",
      "declarar|simplificada|contador|receita federal",
      "file|simplified|accountant"
    ],
    "reply": {
      "pt": "# A declaração do imposto de renda é feita no programa oficial da Receita Federal, de fevereiro a maio.\n\nQuem tem direito à declaração simplificada pode usar o programa sozinho, sem contador. A Receita republica todo ano a tabela de dedução e o limite da simplificada, e por isso este serviço não fixa esses números: o que vale é o que está na página da Receita no momento em que você declara.\n\nA gente nunca pede seu CPF ou sua senha, e não fecha a declaração por você.\n\n[1](https://www.gov.br/receitafederal/pt-br)",
      "en": "# The income tax return is filed in the Federal Revenue's own programme, from February to May.\n\nIf you are eligible for the simplified return you can use the programme yourself, with no accountant. The Revenue republishes the deduction table and the simplified ceiling every year, which is why this service does not quote them: what counts is what is on the Receita page when you file.\n\nWe never ask for your CPF or password, and we do not file the return for you.\n\n[1](https://www.gov.br/receitafederal/pt-br)"
    },
    "followUps": {
      "pt": [
        "Preciso de contador para declarar?",
        "O que é declaração simplificada?"
      ],
      "en": [
        "Do I need an accountant to file?",
        "What is the simplified return?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "retirement-meuinss",
    "match": [
      "\\binss\\b|meu inss|aposentadoria|aposent|rgps|cnis",
      "(m[eèéêë][uùúûü] [iìíîï][nñ]ss|[aàáâãä]pply f[oòóôõö]r [aàáâãä] b[eèéêë][nñ][eèéêë]f[iìíîï]t|r[eèéêë]t[iìíîï]r[eèéêë]m[eèéêë][nñ]t b[eèéêë][nñ][eèéêë]f[iìíîï]t)",
      "conta gov\\.br|[níi]vel (prata|ouro|b[áa]sico)",
      "gov\\.br account|account level"
    ],
    "reply": {
      "pt": "# O benefício é pedido no Meu INSS, e quase sempre exige uma conta gov.br de nível Prata.\n\nO pedido é on-line: você entra, escolhe o benefício, anexa os documentos e acompanha o andamento pelo protocolo. Se algo estiver errado no seu cadastro, o Meu INSS mostra o motivo antes de você protocolar. A idade e o tempo de contribuição dependem de qual regra se aplica ao seu caso, e é por isso que este serviço não dá uma idade \"certa\" sem olhar o seu histórico.\n\n[1](https://meu.inss.gov.br)",
      "en": "# You apply for the benefit on Meu INSS, and almost always need a gov.br account at Silver level or above.\n\nThe application is online: you sign in, pick the benefit, attach the documents and follow it by protocol number. If something in your record is wrong, Meu INSS shows you why before you submit. Age and contribution time depend on which rule applies to your case, which is why this service will not give you a single \"right\" age without looking at your history.\n\n[1](https://meu.inss.gov.br)"
    },
    "followUps": {
      "pt": [
        "Como faço uma conta gov.br?",
        "O que é o nível Prata da conta gov.br?"
      ],
      "en": [
        "How do I get a gov.br account?",
        "What are the account levels?"
      ]
    },
    "exclude": [
      "perdi o (emprego|trabalho)|fui demitid|desempreg|seguro.?desemprego",
      "(i lost my job|lay(ed)? off|unemploy)"
    ],
    "checked": "2026-10-02"
  },
  {
    "id": "health-sus",
    "match": [
      "\\bs[uùúûü]s\\b|\\b[uùúûü]bs\\b|\\b[uùúûü]p[aàáâãä]\\b|pl[aàáâãä][nñ][oòóôõö] d[eèéêë] s[aàáâãä][uùúûü]d[eèéêë]",
      "(h[oòóôõö]w d[oòóôõö][eèéêë]s th[eèéêë] s[uùúûü]s|h[eèéêë][aàáâãä]lth [uùúûü][nñ][iìíîï]t|\\bs[uùúûü]s\\b)",
      "agend\\w* (de )?(consulta|atendiment[oó])|consulta|cart[ãa]o de vacina|vacina[çc][ãa]o|vacino|vacinar",
      "health appointment|vaccinat|health unit|appointment (at|in|for) (a |the )?(health|hospital|clinic|ubs)"
    ],
    "reply": {
      "pt": "# O SUS é federal nas regras, mas quem atende você é a prefeitura ou o estado.\n\nUBS, UPA e hospital são oferta municipal ou estadual. A pasta federal define as regras, a cobertura e o financiamento; quem marca consulta e faz o atendimento é o município. Por isso \"como funciona o SUS na minha cidade\" tem de ser respondido pela secretaria de saúde do seu estado, não pelo Ministério da Saúde.\n\n[1](https://www.gov.br/saude/pt-br)",
      "en": "# The SUS is federal in the rules, but the body that treats you is your city or state.\n\nHealth units, urgent care and hospitals are a municipal or state responsibility. The federal level sets the rules, the coverage and the funding; the municipality books appointments and delivers care. That is why \"how does the SUS work in my city\" has to be answered by your state health secretariat, not by the Ministry of Health.\n\n[1](https://www.gov.br/saude/pt-br)"
    },
    "followUps": {
      "pt": [
        "Como agendo uma consulta?",
        "Onde vejo meu cartão de vacinação?"
      ],
      "en": [
        "How do I book a health appointment?",
        "Where do I see my vaccination record?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "education-fies",
    "match": [
      "\\bf[iìíîï][eèéêë]s\\b|\\bpr[oòóôõö][uùúûü][nñ][iìíîï]\\b|\\b[eèéêë][nñ][eèéêë]m\\b|b[oòóôõö]ls[aàáâãä] d[eèéêë] [eèéêë]st[uùúûü]d[oòóôõö]",
      "(wh[oòóôõö] [cç][aàáâãä][nñ] [uùúûü]s[eèéêë] f[iìíîï][eèéêë]s|f[iìíîï][eèéêë]s|pr[oòóôõö][uùúûü][nñ][iìíîï]|st[uùúûü]d[eèéêë][nñ]t gr[aàáâãä][nñ]t)",
      "educa[çc][ãa]o (municipal|estadual|infantil|fundamental|[mM][ée]dio)",
      "municipal (school|education)|state (school|education)"
    ],
    "reply": {
      "pt": "# O FIES financia o curso em instituição privada, e quem pode usar depende do resultado no Enem.\n\nO FIES é contratado direto com a instituição de ensino, e o contrato começa depois do resultado da primeira fase. Cada linha tem regra própria: cursos técnicos, a segunda fase e a modalidade de educação a distância têm requisitos diferentes. Leia o contrato antes de assinar — ele tem limites que variam por curso e mudam com frequência.\n\n[1](https://www.gov.br/mec/pt-br)",
      "en": "# FIES funds a course at a private institution, and who can use it depends on your Enem score.\n\nYou sign the FIES agreement directly with the institution, and it starts once the first-stage result is out. Each track has its own rules: technical courses, the second stage and distance learning all differ. Read the agreement before you sign — it carries limits that vary by course and change often.\n\n[1](https://www.gov.br/mec/pt-br)"
    },
    "followUps": {
      "pt": [
        "Como funciona o Prouni?",
        "A educação municipal é federal?"
      ],
      "en": [
        "How does Prouni work?",
        "Is municipal education federal?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "work-unemployment",
    "match": [
      "perdi o emprego|demitid|demiss|desemprego|seguro.?desemprego|carteira de trabalho",
      "([iìíîï] (l[oòóôõö]st|g[oòóôõö]t) my j[oòóôõö]b|l[aàáâãä]y[oòóôõö]ff|[uùúûü][nñ][eèéêë]mpl[oòóôõö]y|\\bfgts\\b)"
    ],
    "reply": {
      "pt": "# Depois de uma demissão, três coisas costumam importar: seguro-desemprego, FGTS e carteira de trabalho.\n\nO seguro-desemprego é temporário e tem regra própria: quem estava com carteira assinada há pouco tempo pode não ter direito. O FGTS é seu, com 13º e férias pagos pelo empregador, e o saque exige a Carteira de Trabalho Digital. Me diga quanto tempo você esteve registrado e eu digo por onde começar.\n\n[1](https://www.gov.br/trabalho-e-emprego/pt-br)",
      "en": "# After a job loss, three things usually matter: unemployment insurance, FGTS, and your work record.\n\nUnemployment insurance is temporary and has its own rules: someone signed for a short time may not qualify. FGTS is yours, with the 13th salary and holidays paid by the employer, and withdrawing it needs the Carteira de Trabalho Digital. Tell me how long you were registered and I will say where to start.\n\n[1](https://www.gov.br/trabalho-e-emprego/pt-br)"
    },
    "followUps": {
      "pt": [
        "Como faço o saque do FGTS?",
        "Quem tem direito ao seguro-desemprego?"
      ],
      "en": [
        "How do I withdraw FGTS?",
        "Who qualifies for unemployment insurance?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "business-mei",
    "match": [
      "\\bm[eèéêë][iìíîï]\\b|[aàáâãä]br[iìíîï]r ([uùúûü]m[aàáâãä] )?([eèéêë]mpr[eèéêë]s[aàáâãä]|[nñ][eèéêë]g[oòóôõö][cç][iìíîï][oòóôõö])|s[iìíîï]mpl[eèéêë]s [nñ][aàáâãä][cç][iìíîï][oòóôõö][nñ][aàáâãä]l",
      "([oòóôõö]p[eèéêë][nñ] [aàáâãä] (b[uùúûü]s[iìíîï][nñ][eèéêë]ss|[cç][oòóôõö]mp[aàáâãä][nñ]y)|\\bm[eèéêë][iìíîï]\\b|st[aàáâãä]rt [aàáâãä] b[uùúûü]s[iìíîï][nñ][eèéêë]ss)",
      "cnpj|inscri[çc][ãa]o no simples|nota fiscal",
      "cnpj|simple tax|registration"
    ],
    "reply": {
      "pt": "# Para abrir uma MEI o caminho é Junta Comercial, depois CNPJ, depois Simples Nacional.\n\nSão três órgãos diferentes: a Junta Comercial, que é do seu estado, dá a certidão de exercício; o CNPJ vem do cadastro da Receita; e a inscrição no Simples Nacional é feita no portal da Receita. Antes de decidir pelo MEI, confira o limite de faturamento e de quadro — eles mudam, e um CNAE errado trava a faturação depois.\n\n[1](https://www.gov.br/pt-br/servicos)",
      "en": "# To open an MEI the path is the commercial registry, then the CNPJ, then Simples Nacional.\n\nThree different bodies are involved: the Junta Comercial, which belongs to your state, issues the certificate that the company exists; the CNPJ comes from the Receita register; Simples Nacional is registered on the Receita portal. Before you commit to the MEI, check the turnover and staff limits — they change, and the wrong CNAE locks your invoicing later.\n\n[1](https://www.gov.br/pt-br/servicos)"
    },
    "followUps": {
      "pt": [
        "Qual a diferença entre MEI e Simples Nacional?",
        "Como consulto um CNPJ?"
      ],
      "en": [
        "What is the difference between MEI and Simples Nacional?",
        "How do I look up a CNPJ?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "documents-certidao",
    "match": [
      "[cç][eèéêë]rt[iìíîï]d[aàáâãä][oòóôõö]|[cç][eèéêë]rt[iìíîï]d[oòóôõö][eèéêë]s|[nñ][aàáâãä]s[cç][iìíîï]m[eèéêë][nñ]t[oòóôõö]|[cç][aàáâãä]s[aàáâãä]m[eèéêë][nñ]t[oòóôõö]",
      "([cç][eèéêë]rt[iìíîï]f[iìíîï][cç][aàáâãä]t[eèéêë]|b[iìíîï]rth [cç][eèéêë]rt[iìíîï]f[iìíîï][cç][aàáâãä]t[eèéêë]|[cç][eèéêë]rt[iìíîï]d)",
      "segunda via (do |da )?(cpf|documento)|certid[ãa]o (de )?(trabalho|invent[aá]rio)",
      "second (copy|issue)|cpf copy|work certificate"
    ],
    "reply": {
      "pt": "# Certidão de nascimento, casamento e óbito saem no cartório do seu município, não em gov.br.\n\nA certidão de nascimento é emitida pelo Registro Civil das Pessoas Naturais da cidade onde você nasceu, e muitos cartórios já oferecem atendimento on-line ou por aplicativo. Documentos federais — CPF, certidões da Receita — ficam em órgãos federais, e são outra coisa. Me diga qual documento você precisa que eu digo onde ele sai.\n\nSegunda via do CPF: emitida pela Receita Federal, pode ser solicitada on-line no serviço \"Obter Cartão de CPF\" (https://www.gov.br/pt-br/servicos/obter-cartao-de-cpf) ou nas unidades de atendimento. É gratuita e sai na hora na maioria dos casos.\n\n[1](https://www.gov.br/pt-br/servicos)",
      "en": "# Birth, marriage and death certificates come from your municipality's registry, not from gov.br.\n\nA birth certificate is issued by the Civil Registry of the city where you were born, and many registries now offer online service or an app. Federal documents — your CPF, Receita certificates — sit with federal bodies, and are a different thing. Tell me which document you need and I will say where it comes from.\n\nSecond CPF copy: issued by the Federal Revenue, requestable online via the \"Obter Cartão de CPF\" service (https://www.gov.br/pt-br/servicos/obter-cartao-de-cpf) or at service units. Free and usually issued on the spot.\n\n[1](https://www.gov.br/pt-br/servicos)"
    },
    "followUps": {
      "pt": [
        "Como tiro a segunda via do CPF?",
        "Onde peço a certidão de casamento?"
      ],
      "en": [
        "How do I get a second CPF copy?",
        "Where do I request a marriage certificate?"
      ]
    },
    "exclude": [
      "casamento civil|registro civil|no nascimento do|onde registro",
      "civil marriage|register a birth|register the birth"
    ],
    "checked": "2026-10-02"
  },
  {
    "id": "family-marriage",
    "match": [
      "\\b[cç]asamento civil\\b|registro civil|\\bobito\\b|falecimento|nascimento",
      "([cç][iìíîï]v[iìíîï]l m[aàáâãä]rr[iìíîï][aàáâãä]g[eèéêë]|r[eèéêë]g[iìíîï]st[eèéêë]r [aàáâãä] (b[iìíîï]rth|d[eèéêë][aàáâãä]th)|m[aàáâãä]rr[iìíîï][aàáâãä]g[eèéêë])",
      "cpf.*(casar|casamento)|(casar|casamento).*cpf|união est[áa]vel",
      "cpf.*(marri\\w*|wed)|(marri\\w*|wed).*cpf|marriage|civil registry"
    ],
    "reply": {
      "pt": "# Casamento civil é no cartório, com o oficial de registro civil da sua cidade.\n\nOs requisitos são os da lei: duas pessoas com capacidade civil, sem impedimento, e as testemunhas. O registro no cartório é gratuito — o que costuma custar dinheiro é a cerimônia. Os dois precisam de CPF regular, e o casamento tem efeito no cálculo de impostos da família.\n\n[1](https://www.gov.br/pt-br/servicos)",
      "en": "# A civil marriage is at the registry office, before the civil registrar of your city.\n\nThe requirements come from the law: two people with civil capacity, no impediment, and witnesses. The registry record is free — what usually costs money is the celebration. Both partners need a regular CPF, and the marriage affects the household's tax calculations.\n\n[1](https://www.gov.br/pt-br/servicos)"
    },
    "followUps": {
      "pt": [
        "Preciso de CPF para casar?",
        "Onde registro o nascimento?"
      ],
      "en": [
        "Do I need a CPF to get married?",
        "Where do I register a birth?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "housing-housing",
    "match": [
      "m[iìíîï][nñ]h[aàáâãä] [cç][aàáâãä]s[aàáâãä] m[iìíîï][nñ]h[aàáâãä] v[iìíîï]d[aàáâãä]|h[aàáâãä]b[iìíîï]t[aàáâãä][cç][aàáâãä][oòóôõö]|[aàáâãä]l[uùúûü]g[uùúûü][eèéêë]l s[oòóôõö][cç][iìíîï][aàáâãä]l|[cç]r[eèéêë]d[iìíîï]t[oòóôõö] h[aàáâãä]b[iìíîï]t[aàáâãä][cç][iìíîï][oòóôõö][nñ][aàáâãä]l",
      "(my h[oòóôõö]m[eèéêë] my l[iìíîï]f[eèéêë]|s[oòóôõö][cç][iìíîï][aàáâãä]l h[oòóôõö][uùúûü]s[iìíîï][nñ]g|h[oòóôõö][uùúûü]s[iìíîï][nñ]g [cç]r[eèéêë]d[iìíîï]t)",
      "inscri[çc][ãa]o.{0,60}(m[iìíîï][nñ]h[aàáâãä] [cç][aàáâãä]s[aàáâãä]|h[aàáâãä]b[iìíîï]t[aàáâãä][cç]|a[làáâãä]l[uùúûü]g[uùúûü][eèéêë]l)|(m[iìíîï][nñ]h[aàáâãä] [cç][aàáâãä]s[aàáâãä]|h[aàáâãä]b[iìíîï]t[aàáâãä][cç]|a[làáâãä]l[uùúûü]g[uùúûü][eèéêë]l).{0,60}inscri[çc][ãa]o",
      "(my h[oòóôõö]m[eèéêë] my l[iìíîï]f[eèéêë]|s[oòóôõö][cç][iìíîï][aàáâãä]l h[oòóôõö]uùúûü]s[iìíîï][nñ]g|h[oòóôõö]uùúûü]s[iìíîï][nñ]g [cç]r[eèéêë]d[iìíîï]t).{0,40}(apply|sign up)|(apply|sign up) (for|to) (my h[oòóôõö]m[eèéêë] my l[iìíîï]f[eèéêë]|s[oòóôõö][cç][iìíîï][aàáâãä]l h[oòóôõö]uùúûü]s[iìíîï][nñ]g|h[oòóôõö]uùúûü]s[iìíîï][nñ]g [cç]r[eèéêë]d[iìíîï]t)|where do i apply (for )?(my h[oòóôõö]m[eèéêë] my l[iìíîï]f[eèéêë]|s[oòóôõö][cç][iìíîï][aàáâãä]l h[oòóôõö]uùúûü]s[iìíîï][nñ]g|h[oòóôõö]uùúûü]s[iìíîï][nñ]g [cç]r[eèéêë]d[iìíîï]t)"
    ],
    "reply": {
      "pt": "# Minha Casa, Minha Vida é federal no financiamento, mas a seleção é da prefeitura ou do estado.\n\nO governo federal financia e subsidia; o município faz a seleção e assina o contrato com quem foi escolhido. Isso quer dizer que as regras — renda, tempo de moradia, não ter outro imóvel — são aplicadas localmente, e o programa tem várias linhas, com regras diferentes. Diga onde você mora que eu aponto a prefeitura responsável.\n\n[1](https://www.gov.br/pt-br/servicos)",
      "en": "# My Home, My Life is federal in the financing, but the selection is run by your city or state.\n\nThe federal government finances and subsidises; the municipality runs the selection and signs the contract. That means the rules — income, how long you have lived there, not owning another property — are applied locally, and the programme has several tracks with different rules. Tell me where you live and I will point you to the right city hall.\n\n[1](https://www.gov.br/pt-br/servicos)"
    },
    "followUps": {
      "pt": [
        "Onde faço a inscrição da Minha Casa Minha Vida?",
        "Quem tem direito ao aluguel social?"
      ],
      "en": [
        "Where do I apply for social housing?",
        "Who qualifies for social housing?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "passports-passport",
    "match": [
      "p[aàáâãä]ss[aàáâãä]p[oòóôõö]rt[eèéêë]",
      "(p[aàáâãä]ssp[oòóôõö]rt|f[iìíîï]rst p[aàáâãä]ssp[oòóôõö]rt)",
      "p[oòóôõö]l[iìíîï][cç][iìíîï][aàáâãä] f[eèéêë]d[eèéêë]r[aàáâãä]l|agend\\w* (na |no |de |da |do )?(p[oòóôõö]l[iìíîï][cç][iìíîï][aàáâãä] f[eèéêë]d[eèéêë]r[aàáâãä]l|passaporte)|(p[oòóôõö]l[iìíîï][cç][iìíîï][aàáâãä] f[eèéêë]d[eèéêë]r[aàáâãä]l|passaporte).{0,40}agend\\w*",
      "federal police|book (an? )?appointment (at|in|for)|passport appointment"
    ],
    "reply": {
      "pt": "# O passaporte comum custa R$ 257,25 e é emitido pela Polícia Federal, com atendimento presencial.\n\nA taxa comum é R$ 257,25 por pessoa, paga por GRU no PagTesouro (PIX, cartão ou boleto) depois do formulário. Urgência ou emergência soma R$ 77,17 e totaliza R$ 334,42. Passaporte anterior válido perdido ou danificado sem crime soma R$ 257,25 e totaliza R$ 514,50.\n\nO pedido começa no site da Polícia Federal e termina na mesma unidade da PF, com agendamento: documento de identidade com foto e CPF, e a entrega leva em geral de 6 a 10 dias úteis. Este serviço nunca pede seu CPF ou senha.\n\n[1](https://www.gov.br/pt-br/servicos/obter-passaporte-comum-para-brasileiro)",
      "en": "# A common passport costs R$ 257.25 and is issued by the Federal Police, with an in-person appointment.\n\nThe common fee is R$ 257.25 per person, paid by GRU on PagTesouro (PIX, card or boleto) after the form. Urgency or emergency adds R$ 77.17 for a total of R$ 334.42. A prior valid passport lost or damaged without a crime adds R$ 257.25 for a total of R$ 514.50.\n\nThe request starts on the Federal Police site and ends at the same PF unit, by appointment: photo ID and CPF, and delivery usually takes 6 to 10 business days. This service never asks for your CPF or password.\n\n[1](https://www.gov.br/pt-br/servicos/obter-passaporte-comum-para-brasileiro)"
    },
    "followUps": {
      "pt": [
        "Preciso de visto para viajar?",
        "Como agendo na Polícia Federal?"
      ],
      "en": [
        "Do I need a visa to travel?",
        "How do I book at the Federal Police?"
      ]
    },
    "exclude": [
      "no exterior|abroad|consulado|consulate|itamaraty",
      "abroad|consulate"
    ],
    "checked": "2026-10-02"
  },
  {
    "id": "immigration-visa",
    "match": [
      "\\bv[iìíîï]st[oòóôõö]\\b|r[eèéêë]s[iìíîï]d[eèéêë][nñ][cç][iìíîï][aàáâãä]|[eèéêë]str[aàáâãä][nñ]g[eèéêë][iìíîï]r[oòóôõö]|[iìíîï]m[iìíîï]gr[aàáâãä]",
      "(v[iìíîï]s[aàáâãä]|r[eèéêë]s[iìíîï]d[eèéêë][nñ][cç][eèéêë] p[eèéêë]rm[iìíîï]t|f[oòóôõö]r[eèéêë][iìíîï]g[nñ][eèéêë]r)"
    ],
    "reply": {
      "pt": "# Quem precisa de visto para entrar no Brasil é definido pelo Itamaraty, não pela Polícia Federal.\n\nVisto de turismo, estudo e trabalho são categorias diferentes, com processos e órgãos diferentes. As regras mudam com a política de imigração e podem ser alteradas sem aviso, então confira sempre a data da página que você estiver lendo. O Itamaraty publica a lista de países dispensados de visto.\n\n[1](https://www.gov.br/mre/pt-br)",
      "en": "# Who needs a visa to enter Brazil is set by the Itamaraty, not by the Federal Police.\n\nTourism, study and work visas are separate categories, with separate processes and bodies. The rules move with immigration policy and can change without notice, so always check the date on whatever page you are reading. The Itamaraty publishes the list of countries that do not need a visa.\n\n[1](https://www.gov.br/mre/pt-br)"
    },
    "followUps": {
      "pt": [
        "Como sei se meu país precisa de visto?",
        "Renovo passaporte no exterior?"
      ],
      "en": [
        "Does my country need a visa?",
        "How do I renew a passport abroad?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "civic-bill",
    "match": [
      "pr[oòóôõö]j[eèéêë]t[oòóôõö] d[eèéêë] l[eèéêë][iìíîï]|d[eèéêë]p[uùúûü]t[aàáâãä]d[oòóôõö]|s[eèéêë][nñ][aàáâãä]d[oòóôõö]r|[cç][aàáâãä]m[aàáâãä]r[aàáâãä]|s[eèéêë][nñ][aàáâãä]d[oòóôõö]|[cç][oòóôõö][nñ]gr[eèéêë]ss[oòóôõö]",
      "(project|bill) of law|congress|my (deputy|senator)|legislative|how do i follow a bill",
      "vota[çc][ãa]o|resultado da vota|di[áa]rio oficial|dou eletr[oô]nico",
      "voting|voting result|gazette"
    ],
    "reply": {
      "pt": "# Para acompanhar um projeto de lei, o lugar é a Câmara ou o Senado, onde ele está tramitando.\n\nCada uma das Casas tem uma página pública da proposição com a situação atual, o texto e o histórico de votação, e ambas têm APIs abertas para consultar tudo isso em JSON. O que você vê ali ainda não é lei: só vira lei depois de aprovada, sancionada e publicada no Diário Oficial da União.\n\n[1](https://www.camara.leg.br)",
      "en": "# To follow a bill, go to the Chamber or the Senate, where it is currently moving.\n\nEach chamber has a public page for the proposal with its current status, the text and the voting history, and both have open APIs for all of that as JSON. What you see there is not yet law: it only becomes law once approved, sanctioned and published in the official gazette.\n\n[1](https://www.camara.leg.br)"
    },
    "followUps": {
      "pt": [
        "Como descubro quem é o meu deputado?",
        "Onde vejo o resultado de uma votação?"
      ],
      "en": [
        "How do I find my deputy?",
        "Where do I see a voting result?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "transport-fine",
    "match": [
      "m[uùúûü]lt[aàáâãä]|d[eèéêë]tr[aàáâãä][nñ]|\\b[cç][nñ]h\\b|tr[aàáâãä][nñ]s[iìíîï]t[oòóôõö]|[iìíîï][nñ]fr[aàáâãä][cç][aàáâãä][oòóôõö]",
      "(tr[aàáâãä]ff[iìíîï][cç] f[iìíîï][nñ][eèéêë]|[aàáâãä]pp[eèéêë][aàáâãä]l [aàáâãä] f[iìíîï][nñ][eèéêë]|dr[iìíîï]v[iìíîï][nñ]g l[iìíîï][cç][eèéêë][nñ][cç][eèéêë]|\\b[cç][nñ]h\\b)",
      "prontu[áa]rio|autua[çc][õo]es|pontos na cnh|recorr",
      "driving record|points|appeal|fines?"
    ],
    "reply": {
      "pt": "# Multa e CNH são do Detran do seu estado, não de um órgão federal.\n\nA notificação chega pelo Detran, e o recurso é digital na plataforma do próprio estado, em geral a mesma que emite a CNH. O prazo para recorrer é curto e conta da notificação, então confira a data nela e na página do Detran do seu estado.\n\n[1](https://www.gov.br/transportes/pt-br)",
      "en": "# Fines and driving licences belong to your state's Detran, not to a federal body.\n\nThe notice comes from the Detran, and the appeal is digital on the state's own platform, usually the one that issues your licence. The window to appeal is short and runs from the notice, so check the date on it and on your state Detran page.\n\n[1](https://www.gov.br/transportes/pt-br)"
    },
    "followUps": {
      "pt": [
        "Como vejo o prontuário do condutor?",
        "Onde consulto as autuações?"
      ],
      "en": [
        "Where do I check my driving record?",
        "Where do I look up fines?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "energy-bill",
    "match": [
      "[cç][oòóôõö][nñ]t[aàáâãä] d[eèéêë] l[uùúûü]z|[eèéêë][nñ][eèéêë]rg[iìíîï][aàáâãä] [eèéêë]l[eèéêë]tr[iìíîï][cç][aàáâãä]|tarif[aàáâãä] (de |da |do )?[eèéêë]nerg|[eèéêë]nerg[iìíîï]a.{0,40}tarif[aàáâãä]|b[aàáâãä][nñ]d[eèéêë][iìíîï]r[aàáâãä] t[aàáâãä]r[iìíîï]f[aàáâãä]r[iìíîï][aàáâãä]|[aàáâãä][nñ][eèéêë][eèéêë]l",
      "([eèéêë]l[eèéêë][cç]tr[iìíîï][cç][iìíîï]ty b[iìíîï]ll|[eèéêë][nñ][eèéêë]rgy t[aàáâãä]r[iìíîï]ff|[cç][oòóôõö][nñ]t[aàáâãä] d[eèéêë] l[uùúûü]z)",
      "solar|bandeira tarif|gerador",
      "solar|tariff flag|generator"
    ],
    "reply": {
      "pt": "# Conta de luz você reclama com a concessionária do seu estado; regulação é com a ANEEL.\n\nA concessionária emite a fatura e resolve medidor, ligação e religamento. A ANEEL entra quando o problema é a regulação: tarifa injusta, corte indevido, demora no religamento. Reclame primeiro na concessionária, porque é lá que o prazo de resposta vale. Tarifa e bandeira mudam, então este serviço não anuncia valor.\n\n[1](https://www.gov.br/mme/pt-br)",
      "en": "# You complain about your electricity bill to your state's utility; regulation is ANEEL's job.\n\nThe utility issues the bill and handles the meter, the connection and reconnection. ANEEL steps in when the problem is regulatory: an unfair tariff, an illegal cut-off, a slow reconnection. Complain to the utility first, because that is where the response deadline applies. Tariffs and the flag change, so this service does not quote figures.\n\n[1](https://www.gov.br/mme/pt-br)"
    },
    "followUps": {
      "pt": [
        "Como instalo energia solar?",
        "Quem define a bandeira tarifária?"
      ],
      "en": [
        "How do I go solar?",
        "Who sets the tariff flag?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "environment-licence",
    "match": [
      "licen[çc]?a ambiental|licenciamento|orgao licenciador|meio ambiente|\\bibama\\b|\\bicmbio\\b",
      "environmental licen|licensing body|who licenses|ibama",
      "preserva[çc][ãa]o permanente|licenc|orgao licenciador",
      "permanent preservation|licensing body|licence my|licensing authority"
    ],
    "reply": {
      "pt": "# Licenciamento ambiental é feito pelo órgão que licencia o projeto, e isso muda por estado e por atividade.\n\nO IBAMA licencia o que é federal. Estados e municípios licenciam o restante, e vários têm sistema próprio, com etapas e prazos próprios. Antes de protocolar qualquer pedido, descubra quem é o órgão licenciador do seu caso — essa é a primeira pergunta, não a última.\n\n[1](https://www.gov.br/mma/pt-br)",
      "en": "# Environmental licensing is done by whichever body licenses the project, and that changes by state and by activity.\n\nIBAMA licenses what is federal. States and municipalities license the rest, and many run their own system, with their own steps and deadlines. Before you file anything, work out who licenses your case — that is the first question, not the last.\n\n[1](https://www.gov.br/mma/pt-br)"
    },
    "followUps": {
      "pt": [
        "O que é área de preservação permanente?",
        "Como encontro o órgão licenciador?"
      ],
      "en": [
        "What is an area of permanent preservation?",
        "How do I find the licensing body?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "justice-legal-aid",
    "match": [
      "defensoria|juizado|assist[êe]ncia jur[ií]dica|advogad[oa]|(gr[aáàâã]t\\w*|de gra[cç]a).{0,40}(advogado|advogada|defensoria)|(advogado|advogada|defensoria).{0,40}(gr[aáàâã]t\\w*|de gra[cç]a)",
      "(l[eèéêë]g[aàáâãä]l [aàáâãä][iìíîï]d|d[eèéêë]f[eèéêë][nñ]s[oòóôõö]r[iìíîï][aàáâãä]|l[aàáâãä]wy[eèéêë]r|sm[aàáâãä]ll [cç]l[aàáâãä][iìíîï]ms)",
      "legal aid|defensoria|lawyer|small claims",
      "legal aid|defensoria|lawyer|small claims"
    ],
    "reply": {
      "pt": "# Se você não pode pagar um advogado, a Defensoria Pública é o caminho — e é gratuita.\n\nA Defensoria atende quem tem renda baixa e resolve questões cíveis, em regra nos foros da justiça comum. O primeiro passo é procurar a Defensoria do seu estado; a lista de atendimento fica no site do Ministério da Justiça. Este serviço não substitui um advogado.\n\n[1](https://www.gov.br/mj/pt-br)",
      "en": "# If you cannot afford a lawyer, legal aid is the route — and it is free.\n\nLegal aid serves people on low incomes and handles civil matters, generally in the ordinary courts. The first step is to find your state's Defensoria; the list of offices is on the Ministry of Justice site. This service does not stand in for a lawyer.\n\n[1](https://www.gov.br/mj/pt-br)"
    },
    "followUps": {
      "pt": [
        "O que é um juizado especial?",
        "Como sei se tenho direito à Defensoria?"
      ],
      "en": [
        "What is a small claims court?",
        "How do I know if I qualify for legal aid?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "security-rights",
    "match": [
      "d[iìíîï]sq[uùúûü][eèéêë] 100|d[eèéêë][nñ][uùúûü][nñ][cç][iìíîï][aàáâãä]|v[iìíîï][oòóôõö]l[aàáâãä][cç][aàáâãä][oòóôõö] d[eèéêë] d[iìíîï]r[eèéêë][iìíîï]t[oòóôõö]s|p[oòóôõö]l[iìíîï][cç][iìíîï][aàáâãä] f[eèéêë]d[eèéêë]r[aàáâãä]l",
      "(h[uùúûü]m[aàáâãä][nñ] r[iìíîï]ghts|r[eèéêë]p[oòóôõö]rt [aàáâãä] v[iìíîï][oòóôõö]l[aàáâãä]t[iìíîï][oòóôõö][nñ]|d[iìíîï]sq[uùúûü][eèéêë] 100)",
      "an[ôo]nima|\\b190\\b|policia federal|ouvidoria",
      "anonymous|190|federal police|ombudsman"
    ],
    "reply": {
      "pt": "# Violação de direitos humanos se denuncia no Disque 100, da Ouvidoria Nacional dos Direitos Humanos.\n\nO Disque 100 é gratuito, funciona de qualquer telefone e aceita denúncia anônima. Em emergência, ou se você está em risco agora, ligue 190. A Ouvidoria ouve e encaminha para o órgão competente; ela não substitui a polícia em uma urgência.\n\n[1](https://www.gov.br/casacivil/pt-br)",
      "en": "# Human rights violations are reported to Disque 100, the national human rights ombudsman.\n\nDisque 100 is free, works from any phone, and takes anonymous reports. In an emergency, or if you are at risk right now, call 190. The ombudsman listens and forwards to the competent body; it does not replace the police in an emergency.\n\n[1](https://www.gov.br/casacivil/pt-br)"
    },
    "followUps": {
      "pt": [
        "Qual é o telefone da polícia federal?",
        "Como faço uma denúncia anônima?"
      ],
      "en": [
        "What is the Federal Police number?",
        "How do I report anonymously?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "money-selic",
    "match": [
      "\\bs[eèéêë]l[iìíîï][cç]\\b|\\b[iìíîï]p[cç][aàáâãä]\\b|[cç][aàáâãä]mb[iìíîï][oòóôõö]|d[oòóôõö]l[aàáâãä]r|[iìíîï][nñ]fl[aàáâãä][cç][aàáâãä][oòóôõö]",
      "(s[eèéêë]l[iìíîï][cç]|[iìíîï]p[cç][aàáâãä]|[eèéêë]x[cç]h[aàáâãä][nñ]g[eèéêë] r[aàáâãä]t[eèéêë]|[iìíîï][nñ]fl[aàáâãä]t[iìíîï][oòóôõö][nñ])"
    ],
    "reply": {
      "pt": "# A Selic meta é o juro definido pelo Banco Central, e sai na API pública dele.\n\nDá para consultar a série diária direto na API do Banco Central, com a data de cada observação — e a data é o que importa, porque o valor tem defasagem. O IPCA é medido pelo IBGE, não pelo Banco Central. Este serviço só relata o último valor publicado, com a data dele, e não projeta juro nem câmbio.\n\n[1](https://www.bcb.gov.br)",
      "en": "# The Selic rate is the interest rate the Central Bank sets, and it comes out of its open API.\n\nYou can read the daily series straight from the Central Bank's API, with the date of every observation — and the date is the part that matters, because the figure lags. The IPCA is measured by IBGE, not the Central Bank. This service only reports the last published figure with its date, and does not project rates or exchange rates.\n\n[1](https://www.bcb.gov.br)"
    },
    "followUps": {
      "pt": [
        "Qual a diferença entre Selic e CDI?",
        "Quem mede o IPCA?"
      ],
      "en": [
        "What is the difference between Selic and CDI?",
        "Who measures the IPCA?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  },
  {
    "id": "world-abroad",
    "match": [
      "[iìíîï]t[aàáâãä]m[aàáâãä]r[aàáâãä]ty|[eèéêë]mb[aàáâãä][iìíîï]x[aàáâãä]d[aàáâãä]|[cç][oòóôõö][nñ]s[uùúûü]l[aàáâãä]d[oòóôõö]|[nñ][oòóôõö] [eèéêë]xt[eèéêë]r[iìíîï][oòóôõö]r",
      "(f[oòóôõö]r[eèéêë][iìíîï]g[nñ] m[iìíîï][nñ][iìíîï]stry|[eèéêë]mb[aàáâãä]ssy|[cç][oòóôõö][nñ]s[uùúûü]l[aàáâãä]t[eèéêë]|[aàáâãä]br[oòóôõö][aàáâãä]d)"
    ],
    "reply": {
      "pt": "# Fora do Brasil, o serviço do Itamaraty é o consulado, e ele é o seu canal para a maioria dos documentos.\n\nO Itamaraty emite passaporte brasileiro no exterior, homologa documentos e ajuda em emergências. Cada consulado tem o que pode fazer e as regras da sua circunscrição, então comece pela página do consulado da sua região. Em emergência de saúde ou segurança fora do país, o primeiro contato é a sua seguradora de viagem.\n\n[1](https://www.gov.br/mre/pt-br)",
      "en": "# Outside Brazil, the Foreign Ministry's service is the consulate, and it is your channel for most documents.\n\nThe Itamaraty issues Brazilian passports abroad, legalises documents and helps in emergencies. Each consulate has its own scope and its own rules for its district, so start with the page for your region. In a health or security emergency abroad, your travel insurance comes first.\n\n[1](https://www.gov.br/mre/pt-br)"
    },
    "followUps": {
      "pt": [
        "Perdi o passaporte no exterior. E agora?",
        "Como agendo no consulado?"
      ],
      "en": [
        "I lost my passport abroad. What now?",
        "How do I book at the consulate?"
      ]
    },
    "exclude": [],
    "checked": "2026-10-02"
  }
];

const scenarios: Scenario[] = STARTERS.map((s) => ({
  id: s.id,
  priority: 1,
  // Patterns are authored accent-folded (see render-starters.mjs), so a question typed without accents
  // still routes. All of them are matched case-insensitively.
  match: s.match.map((pattern) => new RegExp(pattern, 'i')),
  exclude: s.exclude.map((pattern) => new RegExp(pattern, 'i')),
  reply: s.reply,
  checked: s.checked,
  followUps: s.followUps,
}));

export default scenarios;
