/**
 * Common starting places (approximate town centres), matched before calling the NRCan geolocator so everyday
 * questions ("parks near Rimouski") never depend on the network. Coordinates are only used to rank parks by
 * straight-line distance. Used by the tools (upstream.ts) and the lab fixtures, never by the renderers.
 */
import { TOWNS, type Town } from './towns';

export const CITIES: Town[] = [
  ...TOWNS,
  { names: ['hamilton'], lat: 43.2557, lng: -79.8711, label: { en: 'Hamilton', fr: 'Hamilton' } },
  { names: ['gaspe', 'gaspé'], lat: 48.831, lng: -64.487, label: { en: 'Gaspé', fr: 'Gaspé' } },
  { names: ['banff', 'banff townsite'], lat: 51.178, lng: -115.572, label: { en: 'Banff', fr: 'Banff' } },
  { names: ['canmore'], lat: 51.089, lng: -115.359, label: { en: 'Canmore', fr: 'Canmore' } },
  { names: ['jasper', 'jasper townsite'], lat: 52.873, lng: -118.08, label: { en: 'Jasper', fr: 'Jasper' } },
  { names: ['medicine hat'], lat: 50.042, lng: -110.677, label: { en: 'Medicine Hat', fr: 'Medicine Hat' } },
  { names: ['churchill'], lat: 58.768, lng: -94.165, label: { en: 'Churchill', fr: 'Churchill' } },
  { names: ['moose jaw'], lat: 50.393, lng: -105.535, label: { en: 'Moose Jaw', fr: 'Moose Jaw' } },
  { names: ['swift current'], lat: 50.285, lng: -107.797, label: { en: 'Swift Current', fr: 'Swift Current' } },
  { names: ['tofino'], lat: 49.153, lng: -125.907, label: { en: 'Tofino', fr: 'Tofino' } },
  { names: ['whistler'], lat: 50.116, lng: -122.957, label: { en: 'Whistler', fr: 'Whistler' } },
  { names: ['surrey'], lat: 49.191, lng: -122.849, label: { en: 'Surrey', fr: 'Surrey' } },
  { names: ['burnaby'], lat: 49.249, lng: -122.98, label: { en: 'Burnaby', fr: 'Burnaby' } },
  { names: ['abbotsford'], lat: 49.05, lng: -122.328, label: { en: 'Abbotsford', fr: 'Abbotsford' } },
  { names: ['penticton'], lat: 49.491, lng: -119.589, label: { en: 'Penticton', fr: 'Penticton' } },
  { names: ['vernon'], lat: 50.267, lng: -119.272, label: { en: 'Vernon', fr: 'Vernon' } },
  { names: ['revelstoke'], lat: 50.998, lng: -118.196, label: { en: 'Revelstoke', fr: 'Revelstoke' } },
  { names: ['golden'], lat: 51.297, lng: -116.964, label: { en: 'Golden', fr: 'Golden' } },
  { names: ['cranbrook'], lat: 49.512, lng: -115.769, label: { en: 'Cranbrook', fr: 'Cranbrook' } },
  { names: ['nelson'], lat: 49.493, lng: -117.294, label: { en: 'Nelson', fr: 'Nelson' } },
  { names: ['courtenay'], lat: 49.687, lng: -124.994, label: { en: 'Courtenay', fr: 'Courtenay' } },
  { names: ['campbell river'], lat: 50.024, lng: -125.247, label: { en: 'Campbell River', fr: 'Campbell River' } },
  { names: ['prince rupert'], lat: 54.315, lng: -130.321, label: { en: 'Prince Rupert', fr: 'Prince Rupert' } },
  { names: ['barrie'], lat: 44.389, lng: -79.69, label: { en: 'Barrie', fr: 'Barrie' } },
  { names: ['owen sound'], lat: 44.567, lng: -80.943, label: { en: 'Owen Sound', fr: 'Owen Sound' } },
  { names: ['windsor'], lat: 42.317, lng: -83.036, label: { en: 'Windsor', fr: 'Windsor' } },
  { names: ['kitchener', 'waterloo'], lat: 43.452, lng: -80.492, label: { en: 'Kitchener', fr: 'Kitchener' } },
  { names: ['guelph'], lat: 43.545, lng: -80.248, label: { en: 'Guelph', fr: 'Guelph' } },
  { names: ['mississauga'], lat: 43.589, lng: -79.644, label: { en: 'Mississauga', fr: 'Mississauga' } },
  { names: ['brampton'], lat: 43.731, lng: -79.762, label: { en: 'Brampton', fr: 'Brampton' } },
  { names: ['niagara falls'], lat: 43.09, lng: -79.084, label: { en: 'Niagara Falls', fr: 'Niagara Falls' } },
  { names: ['st catharines', 'st. catharines'], lat: 43.159, lng: -79.247, label: { en: 'St. Catharines', fr: 'St. Catharines' } },
  { names: ['oshawa'], lat: 43.897, lng: -78.866, label: { en: 'Oshawa', fr: 'Oshawa' } },
  { names: ['peterborough'], lat: 44.305, lng: -78.32, label: { en: 'Peterborough', fr: 'Peterborough' } },
  { names: ['north bay'], lat: 46.309, lng: -79.461, label: { en: 'North Bay', fr: 'North Bay' } },
  { names: ['sault ste marie', 'sault ste. marie', 'sault-sainte-marie'], lat: 46.522, lng: -84.346, label: { en: 'Sault Ste. Marie', fr: 'Sault Ste. Marie' } },
  { names: ['timmins'], lat: 48.477, lng: -81.33, label: { en: 'Timmins', fr: 'Timmins' } },
  { names: ['kenora'], lat: 49.767, lng: -94.489, label: { en: 'Kenora', fr: 'Kenora' } },
  { names: ['gatineau'], lat: 45.477, lng: -75.701, label: { en: 'Gatineau', fr: 'Gatineau' } },
  { names: ['laval'], lat: 45.606, lng: -73.712, label: { en: 'Laval', fr: 'Laval' } },
  { names: ['longueuil'], lat: 45.531, lng: -73.518, label: { en: 'Longueuil', fr: 'Longueuil' } },
  { names: ['levis', 'lévis'], lat: 46.804, lng: -71.178, label: { en: 'Lévis', fr: 'Lévis' } },
  { names: ['drummondville'], lat: 45.884, lng: -72.484, label: { en: 'Drummondville', fr: 'Drummondville' } },
  { names: ['rouyn-noranda'], lat: 48.236, lng: -79.023, label: { en: 'Rouyn-Noranda', fr: 'Rouyn-Noranda' } },
  { names: ["val-d'or", "val d'or", 'val-dor'], lat: 48.098, lng: -77.797, label: { en: 'Val-d’Or', fr: 'Val-d’Or' } },
  { names: ['sept-iles', 'sept-îles'], lat: 50.212, lng: -66.376, label: { en: 'Sept-Îles', fr: 'Sept-Îles' } },
  { names: ['baie-comeau'], lat: 49.217, lng: -68.148, label: { en: 'Baie-Comeau', fr: 'Baie-Comeau' } },
  { names: ['tadoussac'], lat: 48.147, lng: -69.715, label: { en: 'Tadoussac', fr: 'Tadoussac' } },
  { names: ['bathurst'], lat: 47.619, lng: -65.651, label: { en: 'Bathurst', fr: 'Bathurst' } },
  { names: ['edmundston'], lat: 47.373, lng: -68.325, label: { en: 'Edmundston', fr: 'Edmundston' } },
  { names: ['miramichi'], lat: 47.029, lng: -65.501, label: { en: 'Miramichi', fr: 'Miramichi' } },
  { names: ['truro'], lat: 45.365, lng: -63.28, label: { en: 'Truro', fr: 'Truro' } },
  { names: ['yarmouth'], lat: 43.837, lng: -66.117, label: { en: 'Yarmouth', fr: 'Yarmouth' } },
  { names: ['summerside'], lat: 46.395, lng: -63.79, label: { en: 'Summerside', fr: 'Summerside' } },
  { names: ['gander'], lat: 48.954, lng: -54.609, label: { en: 'Gander', fr: 'Gander' } },
  { names: ['grand falls-windsor'], lat: 48.936, lng: -55.665, label: { en: 'Grand Falls-Windsor', fr: 'Grand Falls-Windsor' } },
  { names: ['happy valley-goose bay', 'goose bay'], lat: 53.302, lng: -60.326, label: { en: 'Happy Valley-Goose Bay', fr: 'Happy Valley-Goose Bay' } },
  { names: ['labrador city'], lat: 52.943, lng: -66.914, label: { en: 'Labrador City', fr: 'Labrador City' } },
  { names: ['hay river'], lat: 60.816, lng: -115.786, label: { en: 'Hay River', fr: 'Hay River' } },
  { names: ['fort smith'], lat: 60.005, lng: -111.888, label: { en: 'Fort Smith', fr: 'Fort Smith' } },
  { names: ['rankin inlet'], lat: 62.809, lng: -92.085, label: { en: 'Rankin Inlet', fr: 'Rankin Inlet' } },
];
