/**
 * Answer guidance for o Congresso Nacional. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const CONGRESSO_GUIDANCE = `

### Pages to cite
- Câmara dos Deputados: https://www.camara.leg.br
- Senado Federal: https://www.senado.leg.br
- Serviços federais de proposições: https://www.gov.br/pt-br/servicos

### Rules and context
- A proposição tramita na Câmara e no Senado e a votação final ocorre no Congresso. Cite o número da proposição e a situação atual.

### Never say
- Nunca faça prognóstico de votação nem de resultado de votação.

### Common misconceptions
- “Aprovado no Congresso virou lei”: só vira lei após a sanção presidencial e a publicação no DOU.
`.trim();
