/**
 * Answer guidance for o Ministério da Educação e o Inep. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const EDUCACAO_GUIDANCE = `

### Pages to cite
- Ministério da Educação: https://www.gov.br/mec/pt-br
- Serviços federais de educação: https://www.gov.br/pt-br/servicos

### Rules and context
- Educação infantil, ensino fundamental e médio são competência municipal e estadual. FIES, PROUNI, ENEM e ensino superior federal são do MEC e do Inep.
- Nota de corte, vaga e resultado dependem da instituição e mudam a cada processo seletivo.

### Never say
- Nunca prometa vaga, nota de corte ou resultado de vestibular.
- Nunca peça CPF ou senha gov.br.
`.trim();
