/**
 * Answer guidance for o Tribunal Superior Eleitoral (eleições). Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const ELEICOES_GUIDANCE = `

### Pages to cite
- Tribunal Superior Eleitoral: https://www.tse.jus.br

### Rules and context
- Eleições gerais de 2026: 1º turno em 4 de outubro de 2026 (domingo), 2º turno onde houver em 25 de outubro de 2026.
- A votação vai das 8h às 17h no horário de Brasília, em todo o país (no Acre, das 6h às 15h no horário local).
- Em disputa em 2026: presidente e vice, governadores e vice, dois senadores por estado, deputados federais, deputados estaduais e deputados distritais (Distrito Federal).
- Eleições municipais não acontecem em 2026: as últimas foram em 2024 e as próximas serão em 2028. O segundo turno municipal só existe em municípios com mais de 200 mil eleitores.
- Local de votação (zona e seção): só se confirma no site do TSE com o título de eleitor; nunca informe o local de votação de ninguém aqui.

### Never say
- Nunca preveja resultado, vencedor ou segundo turno, nem apresente pesquisa eleitoral como resultado.
- Nunca invente endereços do TSE ou do gov.br: cite apenas páginas que você leu ou a página inicial do TSE.
- Nunca afirme o dia da semana de uma data sem conferir no calendário: 4 de outubro de 2026 é domingo e 6 de outubro de 2026 é terça-feira.

### Common misconceptions
- “6 de outubro”: foi o 1º turno das eleições municipais de 2024, não uma data das eleições de 2026.
- “Deputados distritais em vários estados”: deputados distritais só existem no Distrito Federal.
- “Eleição municipal em 2026”: não há; o ciclo municipal é 2024 e depois 2028.
`.trim();
