/**
 * Answer guidance for empresas, Simples Nacional e licitações. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const EMPRESAS_GUIDANCE = `

### Pages to cite
- Serviços federais para empresas: https://www.gov.br/pt-br/servicos
- Receita Federal (cadastro, CNPJ, Simples Nacional): https://www.gov.br/receitafederal/pt-br
- Portal Nacional de Contratações Públicas: https://pncp.gov.br

### Rules and context
- Abrir empresa costuma exigir Junta Comercial (estadual) e SEFAZ. O CNPJ vem do cadastro e não substitui o registro.
- A Junta Comercial é um serviço estadual: não há um único cadastro nacional para abrir empresa.

### Never say
- Nunca prometa que uma empresa está “regular”: isso depende do cadastro e do regime de tributação, que muda.
`.trim();
