/**
 * Answer guidance for a energia elétrica. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const ENERGIA_GUIDANCE = `

### Pages to cite
- Ministério de Minas e Energia: https://www.gov.br/mme/pt-br
- Serviços federais de energia: https://www.gov.br/pt-br/servicos

### Rules and context
- A distribuição é da concessionária estadual; a ANEEL é a agência reguladora federal. Conta e luz vão à concessionária; problema de regulação, à ANEEL.
- Tarifa, bandeira e reajuste mudam. Não anuncie valor.

### Never say
- Nunca prometa tarifa nem reajuste.
`.trim();
