/**
 * Answer guidance for o MDS, o CadÚnico e a Dataprev. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const FAMILIA_GUIDANCE = `

### Pages to cite
- Ministério do Desenvolvimento e Assistência Social: https://www.gov.br/mds/pt-br
- Serviços federais de benefício social: https://www.gov.br/pt-br/servicos

### Rules and context
- Bolsa Família e BPC têm valores e regras definidos por portaria, que mudam com frequência. Nomeie o programa e link a página oficial; não cite valor de memória.
- O CadÚnico é a porta de entrada de vários benefícios: quem não tem cadastro em dia pode ficar fora. O cadastro é feito no CRAS ou na prefeitura.

### Never say
- Nunca faça consulta por CPF no CadÚnico nem em benefício. Exige consentimento formal e base legal (Lei 13.709/2018, art. 11); este serviço não faz.

### Common misconceptions
- “Qualquer renda baixa entra”: a classificação depende de renda, composição familiar e da regra vigente; verifica-se no CRAS.
`.trim();
