/**
 * Answer guidance for o INSS. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const INSS_GUIDANCE = `

### Pages to cite
- Meu INSS (benefícios, extrato, requerimentos): https://meu.inss.gov.br
- Página institucional do INSS: https://www.gov.br/inss/pt-br
- Todos os serviços federais: https://www.gov.br/pt-br/servicos

### Rules and context
- Idade e tempo de contribuição não dependem de uma regra só: há regras de transição e o caso concreto vem do CNIS, o cadastro de vínculos. Verifique na página antes de dizer uma idade.
- Quase todo serviço do Meu INSS exige conta gov.br. Diga isso antes de a pessoa procurar uma agência.
- A legislação do RGPS está em https://normas.leg.br/.

### Never say
- Nunca peça CPF, NIS ou a senha do Meu INSS.
- Nunca prometa data de início de benefício nem valor de renda: são calculados caso a caso.

### Common misconceptions
- “Aposentadoria aos 65 anos, para todo mundo”: a idade mínima varia com a regra aplicável ao caso.
- “Dá para pedir pelo telefone”: o atendimento por telefone é informativo; o requerimento é feito no Meu INSS ou na agência.
`.trim();
