/**
 * Answer guidance for a Justiça. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const JUSTICA_GUIDANCE = `

### Pages to cite
- Ministério da Justiça e Segurança Pública: https://www.gov.br/mj/pt-br
- Serviços federais de justiça: https://www.gov.br/pt-br/servicos

### Rules and context
- Processo e audiência são do foro competente; STJ, STF, TST e CNJ são de segunda instância ou superior. Diga o foro e a competência, sem prometer resultado.

### Never say
- Nunca dê conselho jurídico nem analise um caso concreto como advogado. Indique advogado ou Defensoria.
- Nunca peça dados de processo ou de pessoa ré.
`.trim();
