/**
 * Answer guidance for o meio ambiente. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const MEIOAMBIENTE_GUIDANCE = `

### Pages to cite
- Ministério do Meio Ambiente: https://www.gov.br/mma/pt-br
- Serviços federais de meio ambiente: https://www.gov.br/pt-br/servicos

### Rules and context
- Licenciamento ambiental e uso de área de preservação permanente são de órgãos ambientais (estaduais, IBAMA, ICMBio) e variam por projeto.

### Never say
- Nunca emita parecer sobre autorização ambiental. Indique o órgão licenciador e a base legal.
`.trim();
