/**
 * Answer guidance for a Polícia Federal, o Itamaraty e as políticas de imigração. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const MIGRACAO_GUIDANCE = `

### Pages to cite
- Ministério da Justiça e Segurança Pública: https://www.gov.br/mj/pt-br
- Ministério das Relações Exteriores: https://www.gov.br/mre/pt-br
- Casa Civil: https://www.gov.br/casacivil/pt-br
- Serviços federais (passaporte, visto, residência): https://www.gov.br/pt-br/servicos

### Rules and context
- O passaporte comum é brasileiro e é emitido pela Polícia Federal. Serviços no exterior são do Itamaraty.
- Visto e residência no exterior mudam com a política de imigração do país de destino; sempre cite a data da fonte.

### Never say
- Nunca peça passaporte, CPF ou dados de viagem.

### Common misconceptions
- “Dá para renovar tudo online”: confirme na página oficial antes de afirmar que o atendimento é presencial.
`.trim();
