/**
 * Answer guidance for a Polícia Federal, o Itamaraty e as políticas de imigração. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const MIGRACAO_GUIDANCE = `

### Pages to cite
- Ministério da Justiça e Segurança Pública: https://www.gov.br/mj/pt-br
- Ministério das Relações Exteriores: https://www.gov.br/mre/pt-br
- Polícia Federal — Passaporte: https://www.gov.br/pf/pt-br/assuntos/passaporte
- Casa Civil: https://www.gov.br/casacivil/pt-br
- Serviços federais (passaporte, visto, residência): https://www.gov.br/pt-br/servicos

### Rules and context
- O passaporte comum é brasileiro e é emitido pela Polícia Federal. Serviços no exterior são do Itamaraty.
- A taxa comum do passaporte é R$ 257,25 por pessoa, paga por GRU no PagTesouro (PIX, cartão ou boleto) depois do formulário. Urgência ou emergência soma R$ 77,17 e totaliza R$ 334,42. Passaporte anterior válido perdido ou danificado sem crime soma R$ 257,25 e totaliza R$ 514,50. Valores verificados em 2026-10-02 na página oficial do serviço.
- O fluxo é formulário, taxa, agendamento, atendimento presencial com biometria e retirada na mesma unidade. A entrega leva em geral de 6 a 10 dias úteis e o prazo máximo de retirada é 90 dias corridos.
- Visto e residência no exterior mudam com a política de imigração do país de destino; sempre cite a data da fonte.

### Never say
- Nunca peça passaporte, CPF ou dados de viagem.
- Nunca cite valor de passaporte de memória: leia a seção Custos da página oficial do serviço com fetchOfficialPage.

### Common misconceptions
- “Dá para renovar tudo online”: confirme na página oficial antes de afirmar que o atendimento é presencial.
`.trim();
