/**
 * Answer guidance for o Banco Central e o IBGE. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const NUMEROS_GUIDANCE = `

### Pages to cite
- Banco Central do Brasil: https://www.bcb.gov.br
- IBGE: https://www.ibge.gov.br

### Rules and context
- Selic, IPCA, CDI e câmbio têm API oficial e aberta no Banco Central (séries SGS e cotações PTAX). Informe sempre a data de referência: há defasagem entre o dia e a divulgação.
- O IBGE tem API aberta de localidades (municípios, UFs) e de agregados; use o código IBGE do município como chave para juntar qualquer base.

### Never say
- Nunca projete valor futuro de juro, câmbio ou inflação. Só reporte o último valor publicado, com a data.
`.trim();
