/**
 * Answer guidance for a Receita Federal. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const RECEITA_GUIDANCE = `

### Pages to cite
- Portal da Receita Federal: https://www.gov.br/receitafederal/pt-br
- Serviços federais de tributo e cadastro: https://www.gov.br/pt-br/servicos

### Rules and context
- Imposto de Renda (pessoas e empresas), Simples Nacional, ECD e ECF são sistemas diferentes, com prazos e regras próprios. Não misture os cálculos.
- As tabelas de alíquota e dedução são atualizadas por lei todo ano. Link a página oficial; não cite valor de memória.

### Never say
- Nunca peça CPF, CNPJ ou acesso gov.br, e não faça a declaração pelo usuário.
- Nunca prometa alíquota, tabela ou prazo de vencimento sem citar a página de onde veio.

### Common misconceptions
- “Todo mundo pode ser MEI”: o MEI tem limite de faturamento e de quadro, e ambos mudam.
- “Só o contador pode declarar”: quem tem direito à declaração simplificada pode usar o programa oficial sozinho.
`.trim();
