#!/usr/bin/env node
// Renders one guidance module per entry in `guidance.data.json`.
//
//   node src/countries/br/knowledge/guidance/render.mjs
//
// The content lives in the JSON, not in the generated `.ts` files, so the Portuguese prose can be edited
// (and reviewed by a native speaker) without touching code. The renderer validates what it writes: every
// ministry has an export, no bullet is cut off mid-sentence, and no stray character slips into the
// template literal that the model will read.
import { readFileSync, writeFileSync } from 'node:fs';

const DATA = JSON.parse(readFileSync(new URL('./guidance.data.json', import.meta.url), 'utf8'));

const SECTIONS = [
  ['Pages to cite', 'cite'],
  ['Rules and context', 'rules'],
  ['Never say', 'never'],
  ['Common misconceptions', 'myths'],
];

const problems = [];
const fail = (m) => {
  problems.push(m);
  console.log('✗ ' + m);
};

const entries = Object.entries(DATA);

// ---- validate every entry before writing anything ---------------------------------------------------
for (const [mod, spec] of entries) {
  const { const: name, ...sections } = spec;

  if (!/^[A-Z][A-Z_]+$/.test(name)) fail(`${mod}: export name ${name} is not CONST_CASE`);
  for (const [, field] of SECTIONS) {
    const items = sections[field];
    // `myths` is optional and rendered with `?? []` below; the other sections must be there.
    if (items === undefined && field === 'myths') continue;
    if (!Array.isArray(items)) {
      fail(`${mod}: ${field} is not an array`);
      continue;
    }
    for (const item of items) {
      if (typeof item !== 'string' || !item.trim()) fail(`${mod}/${field}: empty or non-string bullet`);
      // A bullet is prose ending in punctuation, or ends with a bare https URL. Anything else is truncated.
      if (!(item.endsWith('.') || item.endsWith(')') || /https:\/\/\S+$/.test(item))) {
        fail(`${mod}/${field}: bullet does not end cleanly -> ${item}`);
      }
      if (/`|\$\{|\{\{|\}\}/.test(item)) fail(`${mod}/${field}: template or brace syntax in prose -> ${item}`);
      if (/[　-鿿Ѐ-ӿ]/.test(item)) fail(`${mod}/${field}: unexpected script -> ${item}`);
      if (item !== item.trim()) fail(`${mod}/${field}: bullet has stray whitespace`);
    }
  }
}

// Every generated module must be referenced by the registry, and vice versa.
const registry = readFileSync(new URL('../index.ts', import.meta.url), 'utf8');
for (const mod of Object.keys(DATA)) {
  if (!registry.includes(`./guidance/${mod}`)) fail(`${mod}.ts is generated but not registered in ../index.ts`);
}
for (const m of registry.matchAll(/'\.\/guidance\/(\w+)'/g)) {
  if (!(m[1] in DATA)) fail(`../index.ts imports guidance/${m[1]}, which has no entry in guidance.data.json`);
}

// One bad bullet must not leave half the directory rewritten against the other half: nothing is written
// until every entry, and the registry that imports them, is sound.
if (problems.length) {
  console.log(`\n${problems.length} problem(s); nothing written`);
  process.exit(1);
}

// ---- render ------------------------------------------------------------------------------------------
let written = 0;
for (const [mod, spec] of entries) {
  const { const: name, label, ...sections } = spec;

  const head = [
    '/**',
    ` * Answer guidance for ${label}. Served to the model by the \`officialGuidance\` tool and injected per turn`,
    ' * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`',
    ' * does not apply.',
    ' *',
    ' * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.',
    ' * Edit the JSON, never this file.',
    ' *',
    ' * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked',
    ' * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the',
    ' * page. Cite the specific service page once you have fetched one.',
    ' */',
    '',
  ];

  const body = [`export const ${name} = \``];
  for (const [heading, field] of SECTIONS) {
    const items = sections[field] ?? [];
    if (!items.length) continue;
    body.push('', `### ${heading}`, ...items.map((i) => `- ${i}`));
  }
  body.push('`.trim();', '');

  const out = [...head, ...body].join('\n');
  writeFileSync(new URL(`./${mod}.ts`, import.meta.url), out);
  written++;
  console.log(`✓ guidance/${mod}.ts (${out.split('\n').length} lines)`);
}

console.log(`\n✓ ${written} guidance modules rendered and consistent`);