/**
 * Answer guidance for o Ministério da Saúde. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const SAUDE_GUIDANCE = `

### Pages to cite
- Ministério da Saúde: https://www.gov.br/saude/pt-br
- Serviços federais de saúde: https://www.gov.br/pt-br/servicos

### Rules and context
- UBS, UPA e hospital são oferta municipal ou estadual, não federal. Para “onde tem posto perto de mim”, aponte o buscador da prefeitura ou da secretaria estadual.
- O Cartão SUS (CNS) é emitido no posto de saúde da cidade, não pelo Ministério da Saúde.

### Never say
- Nunca faça busca por dados de saúde de uma pessoa nem por prontuário: são dados pessoais sensíveis (Lei 13.709/2018, art. 5º, II e art. 11).
- Nunca diagnostique nem sugira tratamento.

### Common misconceptions
- “O SUS cobre qualquer procedimento”: a cobertura depende da política nacional e da execução orçamentária do ano.
`.trim();
