/**
 * Answer guidance for o Ministério do Trabalho e Emprego. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const TRABALHO_GUIDANCE = `

### Pages to cite
- Ministério do Trabalho e Emprego: https://www.gov.br/trabalho-e-emprego/pt-br
- Serviços federais de trabalho: https://www.gov.br/pt-br/servicos

### Rules and context
- O CAGED (emprego formal) é publicado mensalmente em arquivo, sem API oficial. Descreva a tendência a partir do arquivo publicado e não invente número.
- A Carteira de Trabalho Digital é consulta pessoal, no aplicativo oficial.

### Never say
- Nunca faça consulta a vínculo de emprego de uma pessoa.
`.trim();
