/**
 * Answer guidance for os transportes. Served to the model by the `officialGuidance` tool and injected per turn
 * by `../router`. Written for Brazil: the Canadian Digital Service corpus in `vendor/cds-ai-answers/`
 * does not apply.
 *
 * GENERATED by `node src/countries/br/knowledge/guidance/render.mjs` from `guidance.data.json`.
 * Edit the JSON, never this file.
 *
 * Only institutional home pages are listed, each on a domain in `pack.sources.allowlist`, checked
 * 2026-10-02. Deep links are deliberately absent: a stale deep link is worse than the body that owns the
 * page. Cite the specific service page once you have fetched one.
 */

export const TRANSPORTE_GUIDANCE = `

### Pages to cite
- Ministério dos Transportes: https://www.gov.br/transportes/pt-br
- Serviços federais de trânsito: https://www.gov.br/pt-br/servicos

### Rules and context
- CNH, reboque e recursos de multa são do Detran do estado. Aponte o Detran, não um órgão federal.
- A ANTT regula transporte rodoviário e ferroviário; o DNIT trata das rodovias federais.

### Never say
- Nunca peça placa, Renavam ou CPF para consultar multa. Informe o órgão e o procedimento.
`.trim();
