/**
 * Snapshot of Transport Canada's EVAP vehicle list (129 rows), read 2026-09-30 from
 * https://tc.canada.ca/en/road-transportation/innovative-technologies/electric-vehicles/electric-vehicle-affordability-program/vehicle-list
 * (page "Date modified" 2026-03-10). Used only when the live list can't be read, and by the lab fixtures.
 */
import type { EvRow } from './ev';

export const EV_SNAPSHOT: EvRow[] = [
  [2027, "Chevrolet", "Bolt", "RS", "BEV", 0],
  [2027, "Chevrolet", "Bolt", "LT", "BEV", 0],
  [2027, "Chevrolet", "Equinox EV", "LT1 AWD", "BEV", 0],
  [2027, "Chevrolet", "Equinox EV", "LT 2", "BEV", 0],
  [2027, "Chevrolet", "Equinox EV", "LT 1", "BEV", 0],
  [2026, "Chevrolet", "Equinox EV", "LT", "BEV", 0],
  [2026, "Chevrolet", "Equinox EV", "LT AWD", "BEV", 0],
  [2025, "Chevrolet", "Equinox EV", "RS", "BEV", 0],
  [2025, "Chevrolet", "Equinox EV", "LT", "BEV", 0],
  [2025, "Chevrolet", "Equinox EV", "LT AWD", "BEV", 0],
  [2026, "Chrysler", "Pacifica", "Select", "PHEV", 1],
  [2026, "Chrysler", "Pacifica", "Pinnacle", "PHEV", 1],
  [2026, "Chrysler", "Pacifica", "100th", "PHEV", 1],
  [2026, "Chrysler", "Pacifica", "Limited", "PHEV", 1],
  [2025, "Chrysler", "Pacifica", "Select", "PHEV", 1],
  [2025, "Chrysler", "Pacifica", "Limited", "PHEV", 1],
  [2025, "Chrysler", "Pacifica", "FAV", "PHEV", 1],
  [2026, "Dodge", "Charger", "Scat Pack", "BEV", 1],
  [2026, "Dodge", "Charger", "R/T", "BEV", 1],
  [2025, "Dodge", "Charger", "R/T", "BEV", 1],
  [2025, "Dodge", "Charger", "Scat Pack", "BEV", 1],
  [2024, "Dodge", "Charger", "R/T", "BEV", 1],
  [2024, "Dodge", "Charger", "Scat Pack", "BEV", 1],
  [2026, "Fiat", "500e", "Icona", "BEV", 0],
  [2026, "Fiat", "500e", "Pop", "BEV", 0],
  [2025, "Fiat", "500e", "Red", "BEV", 0],
  [2025, "Fiat", "500e", "La Prima", "BEV", 0],
  [2025, "Fiat", "500e", "Giorgio Armani", "BEV", 0],
  [2026, "Ford", "Escape Plug-In Hybrid", "", "PHEV", 0],
  [2026, "Ford", "Mach-e", "Select RWD Standard Range", "BEV", 0],
  [2026, "Ford", "Mach-e", "Select eAWD Standard Range", "BEV", 0],
  [2026, "Ford", "Mach-e", "Premium RWD Extended Range", "BEV", 0],
  [2026, "Ford", "Mach-e", "Premium eAWD Standard Range", "BEV", 0],
  [2026, "Ford", "Mach-e", "Premium RWD Standard Range", "BEV", 0],
  [2026, "Ford", "Mach-e", "Select eAWD Extended Range", "BEV", 0],
  [2025, "Ford", "Escape Plug-In Hybrid", "", "PHEV", 0],
  [2024, "Ford", "Escape Plug-In Hybrid", "", "PHEV", 0],
  [2026, "Hyundai", "Kona EV", "Preferred", "BEV", 0],
  [2026, "Hyundai", "Kona EV", "Preferred w/Trend Package", "BEV", 0],
  [2026, "Hyundai", "Kona EV", "Preferred w/Ultimate Package", "BEV", 0],
  [2025, "Hyundai", "Kona EV", "Preferred w/Trend Package", "BEV", 0],
  [2025, "Hyundai", "Kona EV", "Preferred", "BEV", 0],
  [2027, "Kia", "EV3", "Light FWD", "BEV", 0],
  [2027, "Kia", "EV3", "GT-Line Limited FWD", "BEV", 0],
  [2027, "Kia", "EV3", "GT-Line AWD", "BEV", 0],
  [2027, "Kia", "EV3", "GT-Line FWD", "BEV", 0],
  [2027, "Kia", "EV3", "Land AWD", "BEV", 0],
  [2027, "Kia", "EV3", "Land FWD", "BEV", 0],
  [2027, "Kia", "EV3", "Wind AWD", "BEV", 0],
  [2027, "Kia", "EV3", "Wind FWD", "BEV", 0],
  [2027, "Kia", "EV5", "Land FWD", "BEV", 0],
  [2027, "Kia", "EV5", "Wind AWD", "BEV", 0],
  [2027, "Kia", "EV5", "Wind FWD", "BEV", 0],
  [2027, "Kia", "PV5", "Plus", "BEV", 0],
  [2027, "Kia", "PV5", "Basic", "BEV", 0],
  [2027, "Kia", "Sportage PHEV", "EX Premium AWD", "PHEV", 0],
  [2027, "Kia", "Sportage PHEV", "EX AWD", "PHEV", 0],
  [2026, "Kia", "EV4", "WIND", "BEV", 0],
  [2026, "Kia", "EV4", "GT-LINE", "BEV", 0],
  [2026, "Kia", "EV4", "LIGHT", "BEV", 0],
  [2026, "Kia", "EV4", "WIND PREMIUM", "BEV", 0],
  [2026, "Kia", "Niro EV", "WIND +", "BEV", 0],
  [2026, "Kia", "Niro EV", "WIND", "BEV", 0],
  [2026, "Kia", "Niro PHEV", "LX", "PHEV", 0],
  [2026, "Kia", "Niro PHEV", "EX", "PHEV", 0],
  [2026, "Kia", "Niro PHEV", "EX PREMIUM", "PHEV", 0],
  [2026, "Kia", "Sorento PHEV", "LX PHEV", "PHEV", 0],
  [2026, "Kia", "Sportage PHEV", "EX", "PHEV", 0],
  [2026, "Kia", "Sportage PHEV", "EX PREMIUM", "PHEV", 0],
  [2025, "Kia", "EV6", "LIGHT RWD", "BEV", 0],
  [2025, "Kia", "Niro EV", "WIND +", "BEV", 0],
  [2025, "Kia", "Niro EV", "WIND", "BEV", 0],
  [2025, "Kia", "Niro PHEV", "EX PREMIUM", "PHEV", 0],
  [2025, "Kia", "Niro PHEV", "LX", "PHEV", 0],
  [2025, "Kia", "Niro PHEV", "EX", "PHEV", 0],
  [2025, "Kia", "Sportage PHEV", "EX PREMIUM", "PHEV", 0],
  [2024, "Kia", "Niro EV", "WIND +", "BEV", 0],
  [2024, "Kia", "Niro EV", "WIND", "BEV", 0],
  [2027, "Kia", "EV4", "Wind FWD", "BEV", 0],
  [2027, "Kia", "EV4", "GT-Line FWD", "BEV", 0],
  [2027, "Kia", "EV4", "Wind Premium AWD", "BEV", 0],
  [2027, "Kia", "EV4", "Wind Premium FWD", "BEV", 0],
  [2027, "Kia", "EV4", "Wind AWD", "BEV", 0],
  [2027, "Kia", "EV4", "Light FWD", "BEV", 0],
  [2027, "MINI", "Countryman SE All4", "Elementary Edition", "BEV", 0],
  [2026, "Mazda", "CX-70 PHEV", "GS-SC", "PHEV", 0],
  [2026, "Mazda", "CX-90 PHEV", "GS", "PHEV", 0],
  [2026, "Mitsubishi", "Outlander PHEV", "ES", "PHEV", 0],
  [2025, "Mitsubishi", "Outlander PHEV", "ES", "PHEV", 0],
  [2027, "Nissan", "ARIYA", "SV FWD", "BEV", 0],
  [2027, "Nissan", "Leaf", "S", "BEV", 0],
  [2027, "Nissan", "Leaf", "S+", "BEV", 0],
  [2027, "Nissan", "Leaf", "SV+", "BEV", 0],
  [2026, "Nissan", "Leaf", "SV+", "BEV", 0],
  [2026, "Nissan", "Leaf", "S+", "BEV", 0],
  [2026, "Subaru", "Uncharted", "FWD LR", "BEV", 0],
  [2026, "Subaru", "Uncharted", "FWD", "BEV", 0],
  [2026, "Subaru", "Uncharted", "Sport", "BEV", 0],
  [2027, "Subaru", "Solterra", "Limited", "BEV", 0],
  [2027, "Subaru", "Solterra", "Limited Black Cladding", "BEV", 0],
  [2027, "Subaru", "Solterra", "Touring", "BEV", 0],
  [2027, "Subaru", "Solterra", "Touring Black Cladding", "BEV", 0],
  [2027, "Subaru", "Trailseeker", "Touring", "BEV", 0],
  [2027, "Subaru", "Uncharted", "FWD", "BEV", 0],
  [2027, "Subaru", "Uncharted", "FWD Long Range", "BEV", 0],
  [2027, "Subaru", "Uncharted", "Sport", "BEV", 0],
  [2027, "Subaru", "Uncharted", "GT", "BEV", 0],
  [2026, "Tesla", "Model Y", "RWD-B", "BEV", 0],
  [2027, "Toyota", "C-HR", "XSE (AWD)", "BEV", 0],
  [2027, "Toyota", "C-HR", "SE (FWD)", "BEV", 0],
  [2026, "Toyota", "C-HR", "SE (FWD)", "BEV", 0],
  [2026, "Toyota", "C-HR", "XSE (AWD)", "BEV", 0],
  [2026, "Toyota", "Prius Plug-in Hybrid", "XSE Premium", "PHEV", 0],
  [2026, "Toyota", "Prius Plug-in Hybrid", "SE", "PHEV", 0],
  [2026, "Toyota", "Prius Plug-in Hybrid", "Nightshade", "PHEV", 0],
  [2026, "Toyota", "Prius Plug-in Hybrid", "XSE", "PHEV", 0],
  [2026, "Toyota", "RAV4 Plug-In Hybrid", "SE", "PHEV", 0],
  [2026, "Toyota", "bZ", "XLE FWD", "BEV", 0],
  [2027, "Toyota", "Prius Plug-In Hybrid", "XSE", "PHEV", 0],
  [2027, "Toyota", "Prius Plug-In Hybrid", "SE", "PHEV", 0],
  [2027, "Toyota", "Prius Plug-In Hybrid", "XSE Premium", "PHEV", 0],
  [2027, "Toyota", "bZ", "XLE FWD", "BEV", 0],
  [2025, "Volkswagen", "ID.4", "Base", "BEV", 0],
  [2026, "Volvo", "EX30 Single Motor Extended Range", "Plus", "BEV", 0],
  [2026, "Volvo", "EX30 Single Motor Extended Range", "Core", "BEV", 0],
  [2026, "Volvo", "EX30 Single Motor Extended Range", "Ultra", "BEV", 0],
  [2026, "Volvo", "EX30 Twin Motor Performance", "Plus", "BEV", 0],
  [2026, "Volvo", "EX30 Twin Motor Performance", "Ultra", "BEV", 0],
  [2026, "Volvo", "EX30 Twin Motor Performance", "Ultra, Cross Country", "BEV", 0],
];
